import 'package:neat/features/theme_engine/presentation/providers/theme_engine_provider.dart';

class ThemeTemplates {
  ThemeTemplates._();

  // ── constant/constant.dart ────────────────────────────────────────────────

  static String constantBarrel() => r'''import 'package:flutter/material.dart';

part 'app_color.dart';
part 'app_gap.dart';
''';

  // ── constant/app_color.dart ───────────────────────────────────────────────

  static String appColor({
    String seedHex = '0xFF6366F1',
  }) {
    final darkHex = _darkenHex(seedHex, 0.15);
    final subtleHex = _subtleHex(seedHex);
    return '''part of \'constant.dart\';

class Palette {
  Palette._();

  // ── Brand (generated by NEAT Theme Engine) ────────────────────────────────
  static const Color brand = Color($seedHex);
  static const Color brandDark = Color($darkHex);
  static const Color brandSubtle = Color($subtleHex);
  static const Color onBrand = Color(0xFFFFFFFF);

  // ── Neutral ───────────────────────────────────────────────────────────────
  static const Color ink = Color(0xFF121827);
  static const Color muted = Color(0xFF6B7280);
  static const Color mutedLight = Color(0xFFD1D5DB);
  static const Color border = Color(0xFFE5E7EB);
  static const Color canvas = Color(0xFFF9FAFB);
  static const Color surface = Color(0xFFFFFFFF);

  // ── Destructive ───────────────────────────────────────────────────────────
  static const Color destructive = Color(0xFFEF4444);
  static const Color destructiveDark = Color(0xFFDC2626);

  // ── Status ────────────────────────────────────────────────────────────────
  static const Color statusSuccessFg = Color(0xFF16A34A);
  static const Color statusSuccessBg = Color(0x1A16A34A);
  static const Color statusWarningFg = Color(0xFFD97706);
  static const Color statusWarningBg = Color(0x1AD97706);
  static const Color statusErrorFg = Color(0xFFEF4444);
  static const Color statusErrorBg = Color(0x1AEF4444);
  static const Color statusNeutralFg = Color(0xFF6B7280);
  static const Color statusNeutralBg = Color(0x1A6B7280);
}
''';
  }

  // ── constant/app_gap.dart ─────────────────────────────────────────────────

  static String appGap() => r'''part of 'constant.dart';

class Sizes {
  static const double p4 = 4;
  static const double p6 = 6;
  static const double p8 = 8;
  static const double p10 = 10;
  static const double p12 = 12;
  static const double p16 = 16;
  static const double p20 = 20;
  static const double p24 = 24;
  static const double p32 = 32;
  static const double p48 = 48;
  static const double p64 = 64;
}

const SizedBox gapW4 = SizedBox(width: Sizes.p4);
const SizedBox gapW6 = SizedBox(width: Sizes.p6);
const SizedBox gapW8 = SizedBox(width: Sizes.p8);
const SizedBox gapW10 = SizedBox(width: Sizes.p10);
const SizedBox gapW12 = SizedBox(width: Sizes.p12);
const SizedBox gapW16 = SizedBox(width: Sizes.p16);
const SizedBox gapW20 = SizedBox(width: Sizes.p20);
const SizedBox gapW24 = SizedBox(width: Sizes.p24);
const SizedBox gapW32 = SizedBox(width: Sizes.p32);
const SizedBox gapW48 = SizedBox(width: Sizes.p48);
const SizedBox gapW64 = SizedBox(width: Sizes.p64);

const SizedBox gapH4 = SizedBox(height: Sizes.p4);
const SizedBox gapH6 = SizedBox(height: Sizes.p6);
const SizedBox gapH8 = SizedBox(height: Sizes.p8);
const SizedBox gapH10 = SizedBox(height: Sizes.p10);
const SizedBox gapH12 = SizedBox(height: Sizes.p12);
const SizedBox gapH16 = SizedBox(height: Sizes.p16);
const SizedBox gapH20 = SizedBox(height: Sizes.p20);
const SizedBox gapH24 = SizedBox(height: Sizes.p24);
const SizedBox gapH32 = SizedBox(height: Sizes.p32);
const SizedBox gapH48 = SizedBox(height: Sizes.p48);
const SizedBox gapH64 = SizedBox(height: Sizes.p64);
''';

  // ── typography/typography.dart ────────────────────────────────────────────

  static String typographyBarrel({required String packageName}) =>
      '''import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';

part 'font_size.dart';
part 'font_weight.dart';
part 'text_style.dart';
''';

  // ── typography/font_size.dart ─────────────────────────────────────────────

  static String fontSize(Map<TextStyleKey, TextStyleConfig> textStyles) {
    final entries = textStyles.entries
        .map((e) =>
            '  static const double ${e.key.name} = ${e.value.fontSize};')
        .join('\n');
    return '''part of 'typography.dart';

class FontSizeTheme {
  FontSizeTheme._();

$entries
}
''';
  }

  // ── typography/font_weight.dart ───────────────────────────────────────────

  static String fontWeight(String fontFamily) => '''part of 'typography.dart';

class FontFamilyTheme {
  FontFamilyTheme._();

  static String mainFont = '$fontFamily';
}

class FontWeightTheme {
  FontWeightTheme._();

  static const FontWeight black = FontWeight.w900;
  static const FontWeight extraBold = FontWeight.w800;
  static const FontWeight bold = FontWeight.w700;
  static const FontWeight semiBold = FontWeight.w600;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight regular = FontWeight.w400;
  static const FontWeight light = FontWeight.w300;
  static const FontWeight extraLight = FontWeight.w200;
  static const FontWeight thin = FontWeight.w100;
}
''';

  // ── typography/text_style.dart ────────────────────────────────────────────

  static String textStyle(Map<TextStyleKey, TextStyleConfig> textStyles) {
    final getters = textStyles.entries.map((e) {
      final fw = e.value.fontWeight;
      final ls = e.value.letterSpacing.toStringAsFixed(2);
      final h = e.value.height.toStringAsFixed(2);
      return '  static TextStyle get ${e.key.name} =>\n'
          '      _base.copyWith(\n'
          '        fontSize: FontSizeTheme.${e.key.name},\n'
          '        fontWeight: FontWeight.w$fw,\n'
          '        letterSpacing: $ls,\n'
          '        height: $h,\n'
          '      );';
    }).join('\n\n');

    return '''part of 'typography.dart';

class StyleTheme {
  StyleTheme._();

  static final TextStyle _base = TextStyle(
    fontFamily: FontFamilyTheme.mainFont,
    color: Palette.ink,
    fontWeight: FontWeightTheme.regular,
  );

$getters
}
''';
  }

  // ── app_theme_extensions.dart ─────────────────────────────────────────────

  static String appThemeExtensions({required String packageName}) =>
      '''import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';

class AppColors extends ThemeExtension<AppColors> {
  const AppColors({
    required this.brand,
    required this.brandDark,
    required this.brandSubtle,
    required this.statusSuccessFg,
    required this.statusSuccessBg,
    required this.statusWarningFg,
    required this.statusWarningBg,
    required this.statusErrorFg,
    required this.statusErrorBg,
    required this.statusNeutralFg,
    required this.statusNeutralBg,
  });

  final Color brand;
  final Color brandDark;
  final Color brandSubtle;
  final Color statusSuccessFg;
  final Color statusSuccessBg;
  final Color statusWarningFg;
  final Color statusWarningBg;
  final Color statusErrorFg;
  final Color statusErrorBg;
  final Color statusNeutralFg;
  final Color statusNeutralBg;

  static const AppColors light = AppColors(
    brand: Palette.brand,
    brandDark: Palette.brandDark,
    brandSubtle: Palette.brandSubtle,
    statusSuccessFg: Palette.statusSuccessFg,
    statusSuccessBg: Palette.statusSuccessBg,
    statusWarningFg: Palette.statusWarningFg,
    statusWarningBg: Palette.statusWarningBg,
    statusErrorFg: Palette.statusErrorFg,
    statusErrorBg: Palette.statusErrorBg,
    statusNeutralFg: Palette.statusNeutralFg,
    statusNeutralBg: Palette.statusNeutralBg,
  );

  @override
  AppColors copyWith({
    Color? brand,
    Color? brandDark,
    Color? brandSubtle,
    Color? statusSuccessFg,
    Color? statusSuccessBg,
    Color? statusWarningFg,
    Color? statusWarningBg,
    Color? statusErrorFg,
    Color? statusErrorBg,
    Color? statusNeutralFg,
    Color? statusNeutralBg,
  }) => AppColors(
    brand: brand ?? this.brand,
    brandDark: brandDark ?? this.brandDark,
    brandSubtle: brandSubtle ?? this.brandSubtle,
    statusSuccessFg: statusSuccessFg ?? this.statusSuccessFg,
    statusSuccessBg: statusSuccessBg ?? this.statusSuccessBg,
    statusWarningFg: statusWarningFg ?? this.statusWarningFg,
    statusWarningBg: statusWarningBg ?? this.statusWarningBg,
    statusErrorFg: statusErrorFg ?? this.statusErrorFg,
    statusErrorBg: statusErrorBg ?? this.statusErrorBg,
    statusNeutralFg: statusNeutralFg ?? this.statusNeutralFg,
    statusNeutralBg: statusNeutralBg ?? this.statusNeutralBg,
  );

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) return this;
    return AppColors(
      brand: Color.lerp(brand, other.brand, t)!,
      brandDark: Color.lerp(brandDark, other.brandDark, t)!,
      brandSubtle: Color.lerp(brandSubtle, other.brandSubtle, t)!,
      statusSuccessFg: Color.lerp(statusSuccessFg, other.statusSuccessFg, t)!,
      statusSuccessBg: Color.lerp(statusSuccessBg, other.statusSuccessBg, t)!,
      statusWarningFg: Color.lerp(statusWarningFg, other.statusWarningFg, t)!,
      statusWarningBg: Color.lerp(statusWarningBg, other.statusWarningBg, t)!,
      statusErrorFg: Color.lerp(statusErrorFg, other.statusErrorFg, t)!,
      statusErrorBg: Color.lerp(statusErrorBg, other.statusErrorBg, t)!,
      statusNeutralFg: Color.lerp(statusNeutralFg, other.statusNeutralFg, t)!,
      statusNeutralBg: Color.lerp(statusNeutralBg, other.statusNeutralBg, t)!,
    );
  }
}

extension AppThemeContext on BuildContext {
  AppColors get appColors => Theme.of(this).extension<AppColors>()!;
  TextTheme get textTheme => Theme.of(this).textTheme;
  ColorScheme get colorScheme => Theme.of(this).colorScheme;
}
''';

  // ── app_theme.dart (basic ThemeData) ──────────────────────────────────────

  static String appThemeBasic({
    required String packageName,
    double containerRadius = 12.0,
    double cardElevation = 0.0,
    // Elevated button
    double elevatedRadius = 12.0,
    double elevatedHPad = 24,
    double elevatedVPad = 12,
    double elevatedElevation = 4,
    // Filled button
    double filledRadius = 12.0,
    double filledHPad = 24,
    double filledVPad = 12,
    // Outlined button
    double outlinedRadius = 12.0,
    double outlinedHPad = 24,
    double outlinedVPad = 12,
    double outlinedStroke = 1.5,
    // Text button
    double textRadius = 12.0,
    double textHPad = 16,
    double textVPad = 8,
    // Typography
    Map<TextStyleKey, TextStyleConfig> textStyles = kM3Defaults,
  }) {
    final cr = containerRadius.toStringAsFixed(1);
    final el = cardElevation.toStringAsFixed(1);
    // Button radius helpers
    final erStr = elevatedRadius.toStringAsFixed(1);
    final frStr = filledRadius.toStringAsFixed(1);
    final orStr = outlinedRadius.toStringAsFixed(1);
    final trStr = textRadius.toStringAsFixed(1);
    // Padding helpers
    final eHP = elevatedHPad.round();
    final eVP = elevatedVPad.round();
    final fHP = filledHPad.round();
    final fVP = filledVPad.round();
    final oHP = outlinedHPad.round();
    final oVP = outlinedVPad.round();
    final tHP = textHPad.round();
    final tVP = textVPad.round();
    final eEl = elevatedElevation.toStringAsFixed(1);
    final oSt = outlinedStroke.toStringAsFixed(1);

    // Build TextTheme entries only for configured styles
    final textThemeEntries = textStyles.keys.map((k) {
      return '      ${k.name}: StyleTheme.${k.name},';
    }).join('\n');

    // AppBar uses titleLarge if configured, else falls back gracefully
    final hasTitle = textStyles.containsKey(TextStyleKey.titleLarge);

    return '''import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';
import 'package:$packageName/core/theme/typography/typography.dart';
import 'app_theme_extensions.dart';

class AppTheme {
  AppTheme._();

  static ThemeData get light => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: Palette.brand,
      brightness: Brightness.light,
    ),
    extensions: const [AppColors.light],
    textTheme: TextTheme(
$textThemeEntries
    ),
    scaffoldBackgroundColor: Palette.canvas,
    appBarTheme: AppBarTheme(
      backgroundColor: Palette.surface,
      foregroundColor: Palette.ink,
      elevation: 0,
      shadowColor: Colors.transparent,
      surfaceTintColor: Colors.transparent,
      ${hasTitle ? 'titleTextStyle: StyleTheme.titleLarge.copyWith(color: Palette.ink),' : ''}
    ),
    cardTheme: CardThemeData(
      color: Palette.surface,
      elevation: $el,
      shadowColor: Colors.black,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular($cr),
        side: BorderSide(color: $el > 0 ? Colors.transparent : Palette.border),
      ),
      margin: EdgeInsets.zero,
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        elevation: $eEl,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($erStr)),
        textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        padding: const EdgeInsets.symmetric(horizontal: $eHP, vertical: $eVP),
      ),
    ),
    filledButtonTheme: FilledButtonThemeData(
      style: FilledButton.styleFrom(
        backgroundColor: Palette.brand,
        foregroundColor: Palette.onBrand,
        elevation: 0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($frStr)),
        textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        padding: const EdgeInsets.symmetric(horizontal: $fHP, vertical: $fVP),
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        foregroundColor: Palette.brand,
        side: const BorderSide(color: Palette.brand, width: $oSt),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($orStr)),
        textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        padding: const EdgeInsets.symmetric(horizontal: $oHP, vertical: $oVP),
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        foregroundColor: Palette.brand,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($trStr)),
        textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        padding: const EdgeInsets.symmetric(horizontal: $tHP, vertical: $tVP),
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: Palette.surface,
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.border),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.border),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.brand, width: 1.5),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.destructive),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.destructive, width: 1.5),
      ),
      hintStyle: const TextStyle(color: Palette.muted, fontSize: 14),
      errorStyle: const TextStyle(color: Palette.destructive, fontSize: 12),
    ),
    dividerTheme: const DividerThemeData(color: Palette.border, thickness: 1, space: 1),
    dialogTheme: DialogThemeData(
      backgroundColor: Palette.surface,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($cr)),
    ),
    snackBarTheme: SnackBarThemeData(
      backgroundColor: Palette.ink,
      contentTextStyle: const TextStyle(color: Palette.surface, fontSize: 14),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($orStr)),
      behavior: SnackBarBehavior.floating,
    ),
  );

  static ThemeData get dark => light.copyWith(
    colorScheme: ColorScheme.fromSeed(
      seedColor: Palette.brand,
      brightness: Brightness.dark,
    ),
    extensions: const [AppColors.light],
    scaffoldBackgroundColor: const Color(0xFF0F172A),
    appBarTheme: const AppBarTheme(
      backgroundColor: Color(0xFF1E293B),
      foregroundColor: Color(0xFFF1F5F9),
      elevation: 0,
      shadowColor: Colors.transparent,
      surfaceTintColor: Colors.transparent,
    ),
  );
}
''';
  }

  // ── app_theme.dart (flex_color_scheme variant) ────────────────────────────

  /// Generates [app_theme.dart] for the FlexColorScheme approach.
  ///
  /// [customCode] can be:
  /// - **Full file** (starts with `import`): the entire code from the
  ///   FlexColorScheme playground — used almost verbatim, NEAT only injects
  ///   the [AppColors] extension import.
  /// - **Partial config**: just a `FlexThemeData.light(...)` call — embedded
  ///   in NEAT's template.
  /// - **null / empty**: a sensible Material Baseline default is generated.
  static String appThemeFlexColorScheme({
    required String packageName,
    String? customCode,
    Map<TextStyleKey, TextStyleConfig> textStyles = kM3Defaults,
  }) {
    final code = customCode?.trim() ?? '';
    final isFullFile = code.startsWith('import');

    // ── Full file pasted from playground ─────────────────────────────────────
    if (isFullFile) {
      // Inject NEAT's extensions import right after the last import line.
      const extensionsImport =
          "import 'app_theme_extensions.dart';";
      final neatImport =
          "import 'package:$packageName/core/theme/constant/constant.dart';";

      // Find insertion point: after the last `import` line
      final lines = code.split('\n');
      final lastImportIdx =
          lines.lastIndexWhere((l) => l.trimLeft().startsWith('import'));
      final insertAt = lastImportIdx + 1;

      final injected = [
        ...lines.sublist(0, insertAt),
        neatImport,
        extensionsImport,
        ...lines.sublist(insertAt),
      ].join('\n');

      // Inject AppColors extension into both FlexThemeData.light and .dark calls
      // using paren-counting to find the exact closing ) of each call.
      final withExtensions = _injectFlexExtensions(injected);

      return withExtensions;
    }

    // ── Partial config or default ─────────────────────────────────────────────
    final textThemeEntries = textStyles.keys
        .map((k) => '    ${k.name}: StyleTheme.${k.name},')
        .join('\n');

    final bodyConfig = code.isNotEmpty
        ? '  static ThemeData get light => ($code).toTheme.copyWith(\n'
            '    textTheme: _textTheme,\n'
            '    extensions: const [AppColors.light],\n'
            '    scaffoldBackgroundColor: Palette.canvas,\n'
            '  );\n\n'
            '  // Derive dark from light or paste your dark config here\n'
            '  static ThemeData get dark => light.copyWith(\n'
            '    extensions: const [AppColors.light],\n'
            '  );'
        : '  static ThemeData get light => FlexThemeData.light(\n'
            '    scheme: FlexScheme.materialBaseline,\n'
            '    subThemesData: const FlexSubThemesData(\n'
            '      interactionEffects: true,\n'
            '      tintedDisabledControls: true,\n'
            '      useM2StyleDividerInM3: true,\n'
            '      inputDecoratorIsFilled: true,\n'
            '      inputDecoratorBorderType: FlexInputBorderType.outline,\n'
            '      alignedDropdown: true,\n'
            '    ),\n'
            '    visualDensity: FlexColorScheme.comfortablePlatformDensity,\n'
            '    useMaterial3: true,\n'
            '    extensions: const [AppColors.light],\n'
            '  ).copyWith(\n'
            '    textTheme: _textTheme,\n'
            '    scaffoldBackgroundColor: Palette.canvas,\n'
            '  );\n\n'
            '  static ThemeData get dark => FlexThemeData.dark(\n'
            '    scheme: FlexScheme.materialBaseline,\n'
            '    subThemesData: const FlexSubThemesData(\n'
            '      interactionEffects: true,\n'
            '      tintedDisabledControls: true,\n'
            '      blendOnColors: true,\n'
            '      useM2StyleDividerInM3: true,\n'
            '      inputDecoratorIsFilled: true,\n'
            '      inputDecoratorBorderType: FlexInputBorderType.outline,\n'
            '      alignedDropdown: true,\n'
            '    ),\n'
            '    visualDensity: FlexColorScheme.comfortablePlatformDensity,\n'
            '    useMaterial3: true,\n'
            '    extensions: const [AppColors.light],\n'
            '  ).copyWith(\n'
            '    textTheme: _textTheme,\n'
            '  );';

    return '''import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';
import 'package:$packageName/core/theme/typography/typography.dart';
import 'app_theme_extensions.dart';

class AppTheme {
  AppTheme._();

$bodyConfig

  static TextTheme get _textTheme => TextTheme(
$textThemeEntries
  );
}
''';
  }

  // ── theme_mode_controller.dart (riverpod with annotations) ───────────────

  static String themeModeControllerRiverpod({required String packageName}) =>
      '''import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:flutter/material.dart';

part 'theme_mode_controller.g.dart';

@Riverpod(keepAlive: true)
class ThemeModeController extends _\$ThemeModeController {
  @override
  ThemeMode build() => ThemeMode.light;

  void toggle() => state = state == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;

  void setLight() => state = ThemeMode.light;
  void setDark() => state = ThemeMode.dark;
  void setSystem() => state = ThemeMode.system;
}
''';

  // ── theme_mode_controller.dart (riverpod manual) ──────────────────────────

  static String themeModeControllerRiverpodManual() => r'''import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/material.dart';

final themeModeControllerProvider =
    StateNotifierProvider<ThemeModeController, ThemeMode>(
  (ref) => ThemeModeController(),
);

class ThemeModeController extends StateNotifier<ThemeMode> {
  ThemeModeController() : super(ThemeMode.light);

  void toggle() => state = state == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;
  void setLight() => state = ThemeMode.light;
  void setDark() => state = ThemeMode.dark;
  void setSystem() => state = ThemeMode.system;
}
''';

  // ── brightness_theme/brightness_cubit.dart ────────────────────────────────

  static String brightnessCubit() => r'''import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'brightness_state.dart';

class BrightnessCubit extends Cubit<BrightnessState> {
  BrightnessCubit() : super(const BrightnessLight());

  ThemeMode get themeMode =>
      state is BrightnessDark ? ThemeMode.dark : ThemeMode.light;

  void toggle() => state is BrightnessLight
      ? emit(const BrightnessDark())
      : emit(const BrightnessLight());

  void setLight() => emit(const BrightnessLight());
  void setDark() => emit(const BrightnessDark());
}
''';

  static String brightnessCubitState() => r'''part of 'brightness_cubit.dart';

sealed class BrightnessState {
  const BrightnessState();
}

final class BrightnessLight extends BrightnessState {
  const BrightnessLight();
}

final class BrightnessDark extends BrightnessState {
  const BrightnessDark();
}
''';

  // ── brightness_theme/brightness_bloc.dart ────────────────────────────────

  static String brightnessBloc() => r'''import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'brightness_event.dart';
part 'brightness_state.dart';

class BrightnessBloc extends Bloc<BrightnessEvent, BrightnessState> {
  BrightnessBloc() : super(const BrightnessLight()) {
    on<BrightnessToggled>(_onToggled);
    on<BrightnessSetLight>(_onSetLight);
    on<BrightnessSetDark>(_onSetDark);
  }

  ThemeMode get themeMode =>
      state is BrightnessDark ? ThemeMode.dark : ThemeMode.light;

  void _onToggled(BrightnessToggled event, Emitter<BrightnessState> emit) =>
      emit(state is BrightnessLight ? const BrightnessDark() : const BrightnessLight());

  void _onSetLight(BrightnessSetLight event, Emitter<BrightnessState> emit) =>
      emit(const BrightnessLight());

  void _onSetDark(BrightnessSetDark event, Emitter<BrightnessState> emit) =>
      emit(const BrightnessDark());
}
''';

  static String brightnessBlocEvent() => r'''part of 'brightness_bloc.dart';

sealed class BrightnessEvent {
  const BrightnessEvent();
}

final class BrightnessToggled extends BrightnessEvent {
  const BrightnessToggled();
}

final class BrightnessSetLight extends BrightnessEvent {
  const BrightnessSetLight();
}

final class BrightnessSetDark extends BrightnessEvent {
  const BrightnessSetDark();
}
''';

  static String brightnessBlocState() => r'''part of 'brightness_bloc.dart';

sealed class BrightnessState {
  const BrightnessState();
}

final class BrightnessLight extends BrightnessState {
  const BrightnessLight();
}

final class BrightnessDark extends BrightnessState {
  const BrightnessDark();
}
''';

  // ── Private flex injection helpers ───────────────────────────────────────

  /// Returns the index of the `)` that closes the `(` at [openIdx].
  /// Returns -1 if no matching paren is found.
  static int _findMatchingParen(String code, int openIdx) {
    var depth = 0;
    for (var i = openIdx; i < code.length; i++) {
      if (code[i] == '(') depth++;
      if (code[i] == ')') {
        depth--;
        if (depth == 0) return i;
      }
    }
    return -1;
  }

  /// Injects `extensions: const [AppColors.light]` into every
  /// `FlexThemeData.light(...)` and `FlexThemeData.dark(...)` call found in
  /// [code].
  ///
  /// - If the call is already followed by `.copyWith(`, the extension is
  ///   injected at the top of that existing copyWith block.
  /// - Otherwise a new `.copyWith(extensions: const [AppColors.light])` is
  ///   appended right after the closing `)` of the FlexThemeData call.
  ///
  /// Returns [code] unchanged if it already references `AppColors`.
  static String _injectFlexExtensions(String code) {
    if (code.contains('AppColors')) return code;

    var result = code;
    for (final variant in ['FlexThemeData.light(', 'FlexThemeData.dark(']) {
      var searchFrom = 0;
      while (true) {
        final callIdx = result.indexOf(variant, searchFrom);
        if (callIdx == -1) break;

        // Index of the opening `(` of this FlexThemeData call.
        final openParen = callIdx + variant.length - 1;
        final closeParen = _findMatchingParen(result, openParen);
        if (closeParen == -1) {
          searchFrom = callIdx + 1;
          continue;
        }

        // Look at what immediately follows the closing paren (skip whitespace).
        final afterCloseRaw = result.substring(closeParen + 1);
        final afterClose = afterCloseRaw.trimLeft();

        if (afterClose.startsWith('.copyWith(')) {
          // Existing .copyWith — inject inside it at the very beginning.
          final cwStart = result.indexOf('.copyWith(', closeParen + 1);
          final cwOpenParen = cwStart + '.copyWith('.length - 1;
          const inject = '\n    extensions: const [AppColors.light],';
          result = result.substring(0, cwOpenParen + 1) +
              inject +
              result.substring(cwOpenParen + 1);
          searchFrom = cwOpenParen + inject.length + 1;
        } else {
          // No .copyWith — add one right after the closing paren.
          const inject =
              '.copyWith(\n    extensions: const [AppColors.light],\n  )';
          result = result.substring(0, closeParen + 1) +
              inject +
              result.substring(closeParen + 1);
          searchFrom = closeParen + inject.length + 1;
        }
      }
    }
    return result;
  }

  // ── Private hex helpers ───────────────────────────────────────────────────

  /// Darkens an ARGB hex string like '0xFF00DCE5' by [factor] (0.0–1.0).
  static String _darkenHex(String hexARGB, double factor) {
    final v = int.parse(hexARGB.replaceFirst('0x', ''), radix: 16);
    final a = (v >> 24) & 0xFF;
    var r = (v >> 16) & 0xFF;
    var g = (v >> 8) & 0xFF;
    var b = v & 0xFF;
    r = (r * (1 - factor)).round().clamp(0, 255);
    g = (g * (1 - factor)).round().clamp(0, 255);
    b = (b * (1 - factor)).round().clamp(0, 255);
    final result = (a << 24) | (r << 16) | (g << 8) | b;
    return '0x${result.toRadixString(16).padLeft(8, '0').toUpperCase()}';
  }

  /// Returns a low-opacity (10%) version of [hexARGB] for subtle backgrounds.
  static String _subtleHex(String hexARGB) {
    final v = int.parse(hexARGB.replaceFirst('0x', ''), radix: 16);
    final r = (v >> 16) & 0xFF;
    final g = (v >> 8) & 0xFF;
    final b = v & 0xFF;
    // alpha = 0x1A ≈ 10%
    const a = 0x1A;
    final result = (a << 24) | (r << 16) | (g << 8) | b;
    return '0x${result.toRadixString(16).padLeft(8, '0').toUpperCase()}';
  }
}
