import 'package:neat/core/contract/neat_contract.dart';

/// Generates a project-specific `AGENTS.md` **from the `.neat.json` contract**.
///
/// Unlike generic AI-rules files, this is accurate by construction: it only
/// mentions what the project actually contains, it matches the real generated
/// folder layout, and — uniquely — it teaches an agent NEAT's **anchor system**
/// so edits stay consistent with the Workshop.
class AgentsMdTemplate {
  const AgentsMdTemplate._();

  static String generate(NeatContract c) {
    final featureFirst = c.architecture == 'feature_first';
    final hasRiverpod = c.stateManagement == 'riverpod';
    final hasBloc = c.stateManagement == 'bloc';
    final useAnnotations = c.useRiverpodAnnotations && hasRiverpod;
    final builder = c.navigation == 'go_router_builder';
    final hasGoRouter = c.navigation == 'go_router' || builder;
    final hasHttp = c.httpClient != 'none';
    final offline = c.storageStrategy != 'remoteOnly';
    final sync = c.storageStrategy == 'offlineFirstSync';
    final hasCodegen = useAnnotations || c.hasFreezed || c.hasJsonSerializable || builder || hasHttp;
    const pkg = 'local_storage';
    final fbase = featureFirst ? 'lib/features/<feature>' : 'lib/{data,domain,presentation}/<feature>';

    final b = StringBuffer();

    // ── Header ──────────────────────────────────────────────────────────────
    b.writeln('# Agent guide — ${c.projectName}\n');
    b.writeln('Generated by [NEAT](https://github.com/Olivier-plessis/neat). This file is '
        'derived from the project\'s `.neat.json` contract, so it describes **exactly** this '
        "project's stack and layout — keep it in sync if you change the stack.\n");

    // ── Stack table ─────────────────────────────────────────────────────────
    b.writeln('## Stack\n');
    b.writeln('| Area | Choice |');
    b.writeln('|------|--------|');
    b.writeln('| Architecture | ${featureFirst ? 'Feature-first Clean Architecture' : 'Layer-first Clean Architecture'} |');
    if (hasRiverpod) {
      b.writeln('| State management | Riverpod ${useAnnotations ? '(annotations + codegen)' : '(manual Notifier)'} |');
    }
    if (hasBloc) {
      b.writeln('| State management | ${c.useCubit ? 'Cubit (no Events)' : 'Bloc (Events + States)'} |');
    }
    if (hasGoRouter) b.writeln('| Navigation | ${builder ? 'go_router_builder (typed routes)' : 'go_router'} |');
    if (c.useNavigationShell) b.writeln('| Navigation shell | Bottom `NavigationBar` (app boots into the shell) |');
    if (hasHttp) b.writeln('| HTTP client | ${c.httpClient} (typed) |');
    b.writeln('| Local storage | ${offline ? 'Drift (`packages/$pkg`) — ${sync ? 'offline + sync (Outbox)' : 'offline read'}' : 'none (remote-only)'} |');
    if (c.hasFreezed) b.writeln('| Models | freezed${c.hasJsonSerializable ? ' + json_serializable' : ''}, DTO ↔ Entity mappers |');
    if (c.hasEnvied) b.writeln('| Config | envied — 3 flavors (`.env.dev/.staging/.prod`) |');
    b.writeln('| Theme | ${_theme(c.themeApproach)}${c.useScreenUtil ? ', responsive (flutter_screenutil)' : ''} |');
    if (c.extractUiPackage) b.writeln('| UI package | `${c.projectName}_ui` (theme + components extracted) |');
    if (c.generateWidgetbook) b.writeln('| Component catalog | Widgetbook |');
    b.writeln();

    // ── Architecture ────────────────────────────────────────────────────────
    b.writeln('## Architecture (${featureFirst ? 'feature-first' : 'layer-first'})\n');
    b.writeln('```text');
    if (featureFirst) {
      b.writeln('lib/features/<feature>/');
      b.writeln('├── data/          # models (DTOs), sources (api/local), repositories (impl)');
      b.writeln('├── domain/        # entities, repository interfaces, usecases');
      b.writeln('└── presentation/  # pages, providers, ${hasGoRouter ? 'routes, ' : ''}widgets');
    } else {
      b.writeln('lib/data/<feature>/ · lib/domain/<feature>/ · lib/presentation/<feature>/');
    }
    b.writeln('lib/core/            # result, usecases, theme, router, network, env, observers');
    b.writeln('```\n');
    b.writeln('**Rules**\n');
    b.writeln('- Each feature is self-contained — never import another feature\'s internals.');
    b.writeln('- **`domain/` never imports `data/` or `presentation/`** (dependency rule).');
    b.writeln('- Repositories **throw** on failure (no try/catch there — no fallback strategy to justify one). '
        '`UseCase.call` is the *only* place that catches: it converts the exception to a `Failure` via '
        '`NetworkErrorHandler` and returns a `Result<T>` (`lib/core/result/result.dart`).');
    b.writeln('- Usecases extend `UseCase<Params, T>` / `NoParamsUseCase<T>` (`lib/core/usecases/use_case.dart`). '
        '**Always invoke via the callable shorthand — `usecase(params)` — never `usecase.execute(params)` '
        'directly**, which has no error handling of its own.');
    if (offline) {
      b.writeln('- Exception: the offline-first list/detail reads (`getAll`/`getById`) return `Result<T>` '
          '**directly** from the repository — they encapsulate a network→cache fallback strategy, not '
          'boilerplate error handling, so they bypass the generic wrapping (see `featureGetUsecase`).');
    }
    b.writeln();

    // ── State management ────────────────────────────────────────────────────
    if (hasRiverpod) {
      b.writeln('## State management (Riverpod)\n');
      if (useAnnotations) {
        b.writeln('- This project **uses** `@riverpod` / `riverpod_generator` — define providers with '
            'annotations (`@riverpod` or `@Riverpod(keepAlive: true)`), then run codegen.');
      } else {
        b.writeln('- This project defines providers **manually** (`NotifierProvider`) — no `@riverpod` codegen.');
      }
      b.writeln('- `ref.watch` inside `build()`; `ref.read` only in callbacks — never `ref.read` in `build()`.');
      b.writeln('- One `ProviderScope` at the app root already exists — do not nest another.');
      b.writeln('- The dependency graph is wired in **two** files, split by layer:\n'
          '  - `data/repositories/<feature>_repository_providers.dart` — ApiSource, LocalSource, '
          'the repository (abstract-typed)${sync ? ', and the offline sync engine' : ''}.\n'
          '  - `presentation/providers/<feature>_usecase_providers.dart` — the usecases, built from '
          'the repository provider above.\n'
          '  **`presentation/` never references a concrete Data class** (ApiSource, Model, '
          'RepositoryImpl) — only the abstract-typed repository provider exposed from `data/`.');
      if (offline) {
        b.writeln('- **Shared singletons** `appDatabaseProvider` + `networkInfoProvider` live in '
            '`lib/core/providers/infrastructure_providers.dart` — **reference them, never redeclare** '
            '(one Drift connection app-wide).');
      }
      b.writeln();
    }
    if (hasBloc) {
      final kind = c.useCubit ? 'Cubit' : 'Bloc';
      b.writeln('## State management ($kind)\n');
      b.writeln('- Each feature has its own `$kind` under `presentation/${c.useCubit ? 'cubit' : 'bloc'}/`'
          '${c.useCubit ? '' : ' (with a matching `Event` + `State`)'}, wrapped by a `BlocProvider` in its page.');
      b.writeln('- **This is a stub, not wired to a usecase yet**: `load()` has a `// TODO: load data` '
          'placeholder — there is no repository-/usecase-level DI graph for $kind the way the Riverpod '
          'path has (`<feature>_repository_providers.dart` / `<feature>_usecase_providers.dart`). Wire '
          'the usecase call yourself inside `load()`${c.useCubit ? '' : '/`_onLoadRequested`'} and emit a '
          'state carrying the loaded data.');
      b.writeln('- Theme mode is a separate `BrightnessCubit`/`BrightnessBloc` '
          '(`lib/core/theme/brightness_theme/`), provided once at the app root — do not nest another.');
      b.writeln();
    }

    // ── Navigation + anchors ────────────────────────────────────────────────
    if (hasGoRouter) {
      b.writeln('## Navigation (${builder ? 'go_router_builder' : 'go_router'})\n');
      b.writeln('- Router: `lib/core/router/app_router.dart`. Route table: `lib/core/router/routes.dart`. '
          'Path constants: `lib/core/constants/app_route_path.dart`.');
      if (builder) {
        b.writeln('- Routes are **typed** (`@TypedGoRoute`), aggregated via each feature\'s '
            'generated `\$appRoutes`.');
      }
      if (c.useNavigationShell) {
        b.writeln('- The app boots into a **`StatefulShellRoute`** (`lib/core/router/app_shell_route.dart` + '
            '`scaffold_with_nav_bar.dart`); the first feature is the first bottom-nav tab.');
      }
      b.writeln('- **Anchors (do not reformat away):** NEAT inserts new routes at `// neat:route-imports` '
          'and `// neat:route-entries` in `routes.dart`, and constants above `// neat:routes` in '
          '`app_route_path.dart`. Child/shell routes use `// neat:${builder ? 'typed-' : ''}children:<parent>` / '
          '`// neat:shell-branches` / `// neat:shell-destinations`.\n');
    }

    // ── Networking ──────────────────────────────────────────────────────────
    final isSupabase = c.httpClient == 'supabase';
    final isFirebase = c.httpClient == 'firebase';
    b.writeln('## Networking\n');
    if (isSupabase || isFirebase) {
      if (isFirebase) {
        b.writeln('- Backend is **Firebase** (Firestore). The provider is `firestoreProvider` '
            '(`lib/core/network/firebase_provider.dart`); Firebase is initialized in '
            '`lib/core/bootstrap.dart` from `lib/firebase_options.dart` (regenerate with '
            '`flutterfire configure` for production — see `docs/FIREBASE.md`).');
        b.writeln('- Data access goes through `data/sources/<feature>_api_source.dart` '
            '(`collection(...)…`, doc id merged into the model) → repository (throws on failure) → '
            '`UseCase.call` → `Result<T>`. **Never call Firestore from widgets or domain.**');
      } else {
        b.writeln('- Backend is **Supabase** (`supabase_flutter` SDK). The client provider is '
            '`supabaseClientProvider` (`lib/core/network/supabase_provider.dart`); the SDK is '
            'initialized in `lib/core/bootstrap.dart` from the typed env.');
        b.writeln('- Data access goes through `data/sources/<feature>_api_source.dart` (`.from(table)…`) → '
            'repository (throws on failure) → `UseCase.call` → `Result<T>`. **Never call the client from '
            'widgets or domain.**');
      }
      if (c.generateRealtime) {
        final how = isFirebase ? 'Firestore `.snapshots()`' : "`.stream(primaryKey: ['id'])`";
        b.writeln('- **Realtime is on**: the first feature\'s list is a `StreamNotifier` over '
            '$how. The repository exposes `watchAll()`; the screen updates live.');
      }
      if (c.generateStorage) {
        b.writeln('- **Storage is on**: use `StorageService` (`lib/core/storage/storage_service.dart`, '
            'provider `storageServiceProvider`) for uploads/downloads. Sample: `avatar_upload_field.dart`.');
      }
      if (c.generateAuth) {
        b.writeln('- **Auth is on**: `features/auth` (login/signup/forgot) + `AuthController`; a '
            '`RouterNotifier` guards routes (`lib/core/router/router_notifier.dart`).');
        if (c.generateOAuth) {
          b.writeln('- **OAuth is on**: Google + Apple via `FirebaseAuth.signInWithProvider` '
              '(`IAuthRepository.signInWithGoogle/signInWithApple`). Enable the providers in the '
              'Firebase console.');
        }
      }
      if (isFirebase) {
        b.writeln('- **Security Rules**: `firestore.rules` (default-deny + a rule for the first '
            'collection) + `firebase.json`. Deploy with `firebase deploy --only firestore:rules`. '
            'See `docs/FIREBASE.md`.');
      }
      b.writeln();
    } else if (hasHttp) {
      final provider = c.httpClient == 'chopper' ? 'chopperClientProvider' : 'dioProvider';
      b.writeln('- HTTP via **${c.httpClient}**. The client provider is `$provider` '
          '(`lib/core/network/`).');
      b.writeln('- Network access goes through `data/sources/<feature>_api_source.dart` → repository. '
          '**Never call the client from widgets or domain.**');
      b.writeln('- Logging interceptor is pre-wired. The repository throws on a non-2xx response '
          '(${c.httpClient == 'chopper' ? '`unwrapChopperResponse` raises `ChopperApiException`' : 'a `DioException`'}); '
          '`UseCase.call` maps it to `Result<T>` via `NetworkErrorHandler`.\n');
    } else {
      b.writeln('- No HTTP client is enabled. Add one deliberately (and regenerate) rather than calling '
          '`http`/`dio` ad-hoc from widgets.\n');
    }

    // ── Offline / local storage ─────────────────────────────────────────────
    if (offline) {
      b.writeln('## Offline / local storage (Drift)\n');
      b.writeln('- The local DB is a **workspace package**: `packages/$pkg` (Drift). The database is '
          '`packages/$pkg/lib/src/database.dart`.');
      b.writeln('- Each feature has a typed table `<Feature>Rows` + DAO methods, injected at the '
          '`// neat:tables`, `// neat:table-names`, `// neat:daos` anchors.');
      b.writeln('- Repositories are offline-first: read network when online, fall back to the Drift cache.');
      if (sync) {
        b.writeln('- **Writes use the Outbox**: optimistic local write → queued in the Outbox table → '
            'replayed by `SyncService` (`lib/core/sync/sync_service.dart`) when connectivity returns.');
      }
      b.writeln('- `build_runner` runs **per package** — regenerate inside `packages/$pkg` after table changes.\n');
    }

    // ── Internationalisation (slang) ─────────────────────────────────────────
    if (c.generateI18n) {
      b.writeln('## Internationalisation (slang)\n');
      b.writeln('- Type-safe translations: edit the source files in `lib/i18n/` '
          '(`en.i18n.json`/`fr.i18n.json`, or `strings.i18n.csv` if imported), then run '
          '`dart run slang` to regenerate `lib/i18n/strings.g.dart` (slang uses its CLI here, '
          'not build_runner).');
      b.writeln('- Read strings via `context.t.<key>` in widgets (rebuilds on locale change). '
          '`TranslationProvider` wraps the app in `bootstrap`.');
      b.writeln('- Switch locale via `LocaleStore.setLocale(AppLocale.fr)` '
          '(`lib/core/i18n/locale_store.dart`) — it **persists** the choice in '
          'shared_preferences. Do not call `LocaleSettings.setLocale` directly or the '
          'choice won\'t be saved. `LocaleStore.init()` (in bootstrap) restores it on start-up.\n');
    }

    // ── Config / env ────────────────────────────────────────────────────────
    if (c.hasEnvied) {
      b.writeln('## Configuration (envied)\n');
      b.writeln('- Env is **typed** via envied: `.env.dev`, `.env.staging`, `.env.prod` → `lib/core/env/`.');
      b.writeln('- Never read raw env strings in features; use the generated env classes. **Do not commit real secrets.**\n');
    }

    // ── How to add a feature (the unique, anchor-aware part) ─────────────────
    b.writeln('## Adding a feature\n');
    b.writeln('**Preferred — use the NEAT Workshop.** Open this project in NEAT (it reads `.neat.json`) '
        'and generate the feature: it scaffolds data/domain/presentation, wires the route, '
        '${offline ? 'injects the Drift table, ' : ''}and runs codegen — all consistent with this stack. '
        'Prefer this over hand-rolling.\n');
    b.writeln('**If editing by hand, reuse the exact same anchors NEAT uses:**\n');
    b.writeln('1. Mirror an existing feature under `$fbase/{data,domain,presentation}`.');
    if (hasGoRouter) {
      b.writeln('2. Add the path constant in `app_route_path.dart` above `// neat:routes`.');
      b.writeln('3. Wire the route in `routes.dart`: import above `// neat:route-imports`, '
          '${builder ? '`TypedGoRoute` spread' : '`GoRoute`'} above `// neat:route-entries`.');
    }
    if (offline) {
      b.writeln('4. Add the `<Feature>Rows` table + DAO in `packages/$pkg/lib/src/database.dart` '
          'at `// neat:tables` / `// neat:table-names` / `// neat:daos`.');
    }
    if (hasCodegen) b.writeln('5. Run codegen (see **Verification**).');
    b.writeln();

    // ── Conventions ─────────────────────────────────────────────────────────
    b.writeln('## Conventions\n');
    b.writeln('- Files `snake_case.dart`; classes `PascalCase`; private `_camelCase`.');
    b.writeln('- Prefer `const`; avoid `dynamic` without justification; no empty `catch` blocks.');
    b.writeln('- No business logic in widget `build()`; no backend/DB calls from presentation widgets.');
    if (c.hasFreezed) b.writeln('- Entities & models are `freezed`; map DTO → Entity with the generated `toEntity()`.');
    b.writeln('- Do not add a second routing / state-management / backend library.\n');

    // ── Safe / caution / do-not-touch ────────────────────────────────────────
    b.writeln('## Safe to modify\n');
    b.writeln('| Path | Notes |');
    b.writeln('|------|-------|');
    b.writeln('| `$fbase/**` | Feature data/domain/presentation code |');
    b.writeln('| `lib/core/theme/**`${c.extractUiPackage ? ' + `packages/${c.projectName}_ui/**`' : ''} | Visual system |');
    b.writeln('| `test/**` | Unit & widget tests |\n');
    b.writeln('## Modify with caution\n');
    b.writeln('| Path | Why |');
    b.writeln('|------|-----|');
    if (hasGoRouter) b.writeln('| `lib/core/router/**`, `app_route_path.dart` | Central navigation — keep the `// neat:` anchors |');
    if (offline) b.writeln('| `packages/$pkg/lib/src/database.dart` | Drift schema — keep the `// neat:` anchors; regen after edits |');
    b.writeln('| `lib/main.dart`, `lib/core/bootstrap.dart` | Init order (guarded zone, observers${c.hasEnvied ? ', env' : ''}) |');
    b.writeln('| `pubspec.yaml` | Dependency graph |');
    b.writeln('| `.neat.json` | The stack contract NEAT reads — change via NEAT, not by hand |\n');
    b.writeln('## Do not touch\n');
    b.writeln('| Path | Why |');
    b.writeln('|------|-----|');
    b.writeln('| `**/*.g.dart`, `**/*.freezed.dart` | Generated — change the source + regenerate |');
    b.writeln('| `android/`, `ios/`, `macos/`, … | Native project config |');
    if (c.hasEnvied) b.writeln('| `.env.*` with real values | Secrets |');
    b.writeln();

    // ── Verification ────────────────────────────────────────────────────────
    b.writeln('## Verification after changes\n');
    b.writeln('```bash');
    b.writeln('flutter pub get');
    if (hasCodegen) b.writeln('dart run build_runner build --delete-conflicting-outputs');
    if (offline) b.writeln('cd packages/$pkg && dart run build_runner build --delete-conflicting-outputs && cd -');
    b.writeln('flutter analyze   # must be clean');
    b.writeln('flutter test');
    b.writeln('```\n');

    // ── Hard limits ─────────────────────────────────────────────────────────
    b.writeln('## Hard limits\n');
    b.writeln('- Keep generated code **analysis-clean** (0 errors, 0 warnings) — this is NEAT\'s contract.');
    b.writeln('- Never call backend/DB code directly from widgets; respect the layer boundaries.');
    if (hasGoRouter) b.writeln('- Never delete the `// neat:` anchors — the Workshop needs them to add features.');
    b.writeln('- Do not introduce a second state-management or routing library.');
    if (c.hasEnvied) b.writeln('- Never commit real secrets in `.env.*`.');

    return b.toString();
  }

  static String _theme(String approach) => switch (approach) {
        'flexColorScheme' => 'FlexColorScheme',
        'customM3' => 'custom Material 3',
        _ => 'Material 3',
      };
}
