/// Templates for the `<name>_core` workspace package — the shared foundation
/// every other workspace member (feature packages, later phases) depends on
/// instead of depending on the app itself (which a pub workspace forbids: the
/// app already depends on its feature packages, so a cycle would result).
///
/// Phase 1 scope only: `Result`/`Failure`/`UseCase` + a dio-only
/// `NetworkErrorHandler` + a plain (no envied) `dioProvider` + its logging
/// interceptor + `AppLogger` + `AppRoutePath`. Every file is generated by
/// **reusing the existing app-level templates** (`CoreTemplates`/
/// `CoreDartTemplates`), just pointed at the core package's own name instead
/// of the app's — their content has no other app-specific assumptions baked
/// in, so this is a straight mirror of `lib/core/...`, not a rewrite.
class CorePackageTemplates {
  CorePackageTemplates._();

  /// pubspec.yaml for the core package.
  ///
  /// [corePackageName] is the workspace member name, e.g. `myapp_core`.
  /// `resolution: workspace` is required for every member of a Dart workspace.
  /// [httpClient] drives the network client dep: dio for dio/retrofit,
  /// chopper (+ its generator, for `ModelJsonConverter`'s registry file —
  /// the converter itself needs no codegen, but keeping chopper's own dev
  /// tooling alongside it matches how every other package ships it) for
  /// chopper, supabase_flutter/cloud_firestore for supabase/firebase ([hasAuth]/
  /// [hasStorage] add firebase_auth/firebase_storage — supabase's auth/storage
  /// APIs already ship inside supabase_flutter). [localStoragePackage] adds
  /// `connectivity_plus` (for `NetworkInfo`) + a sibling `path:` dep on the
  /// Drift package — every offline-first feature shares the *same*
  /// db/connectivity instances via `infrastructure_providers.dart`, which
  /// lives here. [hasI18n] adds slang's runtime + `shared_preferences` (for
  /// `LocaleStore`'s persistence) — the whole i18n setup is single-sourced
  /// here too, same reasoning as `theme_mode_controller.dart` (see
  /// `LaunchGenerationUsecase`'s i18n block).
  static String pubspec({
    required String corePackageName,
    String httpClient = 'dio',
    String? localStoragePackage,
    bool hasI18n = false,
    bool hasAuth = false,
    bool hasStorage = false,
  }) {
    final clientDep = switch (httpClient) {
      'chopper' => '  chopper: ^8.6.0\n',
      'supabase' => '  supabase_flutter: ^2.14.1\n',
      'firebase' => '  cloud_firestore: ^5.6.0\n'
          '${hasAuth ? '  firebase_auth: ^5.3.4\n' : ''}'
          '${hasStorage ? '  firebase_storage: ^12.4.0\n' : ''}',
      _ => '  dio: ^5.9.2\n',
    };
    final offlineDeps = localStoragePackage != null
        ? '  connectivity_plus: ^7.1.1\n'
              '  $localStoragePackage:\n'
              '    path: ../$localStoragePackage\n'
        : '';
    final i18nDeps = hasI18n
        ? '  slang: ^4.16.0\n'
              '  slang_flutter: ^4.16.0\n'
              '  flutter_localizations:\n'
              '    sdk: flutter\n'
              '  shared_preferences: ^2.3.3\n'
        : '';
    return '''name: $corePackageName
description: "Shared foundation (Result/Failure/UseCase/networking) — generated by NEAT."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^4.0.2
$clientDep$offlineDeps$i18nDeps  logger: ^2.7.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
''';
  }

  /// `Future<T>.fire()` — sugar for `unawaited(this)`, for a fire-and-forget
  /// call whose result is deliberately ignored (e.g. an optimistic write).
  static String futureExtensions() => '''import 'dart:async';

extension FireAndForgetFutureX<T> on Future<T> {
  /// Marks this future as intentionally not awaited.
  void fire() => unawaited(this);
}
''';

  /// pubspec.yaml for a split-out feature workspace package (Phase 1 §6a
  /// step 2). Depends on [corePackageName] via a sibling `path:` dependency —
  /// never on the app itself (a pub workspace forbids cycles, and the app
  /// already depends on every feature package to register its routes).
  /// Versions match NEAT's own default "Riverpod annotations" combo.
  /// [httpClient] drives the network client dep, same as [pubspec] above.
  /// [hasGoRouterBuilder] adds the typed-route generator — its codegen
  /// (`part '<feature>_routes.g.dart'`) runs in this package's own
  /// build_runner pass, same as freezed/riverpod_generator already do.
  /// [localStoragePackage] adds a sibling `path:` dep on the Drift package —
  /// `featureLocalSource()` imports it directly, same as it already does in
  /// the non-split app.
  static String featurePackagePubspec({
    required String featurePackageName,
    required String corePackageName,
    String httpClient = 'dio',
    bool hasGoRouterBuilder = false,
    String? localStoragePackage,
  }) {
    final isChopper = httpClient == 'chopper';
    final clientDeps = isChopper ? '  chopper: ^8.6.0\n' : '  dio: ^5.9.2\n';
    final clientDevDeps = isChopper ? '  chopper_generator: ^8.6.2\n' : '';
    final routerDevDeps = hasGoRouterBuilder ? '  go_router_builder: ^4.3.0\n' : '';
    final localStorageDep = localStoragePackage != null
        ? '  $localStoragePackage:\n    path: ../$localStoragePackage\n'
        : '';
    return '''name: $featurePackageName
description: "Generated by NEAT — a split-out feature package (see ROADMAP.md §6a)."
version: 0.1.0
publish_to: 'none'

environment:
  # >=3.7 required: the generated list page's ListView.separated uses a
  # wildcard pattern (`(_, _) => ...`), which the analyzer rejects as a
  # duplicate declaration below language version 3.7.
  sdk: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  go_router: ^17.2.3
$clientDeps  skeletonizer: ^2.1.3
  $corePackageName:
    path: ../$corePackageName
$localStorageDep

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  freezed: ^3.2.5
  json_serializable: ^6.13.0
$clientDevDeps$routerDevDeps''';
  }
}
