/// Templates for the opt-in `<name>_local_storage` workspace package.
///
/// Phase 1 emits a minimal package that compiles and is wired into the Dart
/// workspace. Phase 2 fills it with the Drift database; Phase 3 wires the
/// witness feature's local-first repository on top.
class LocalStorageTemplates {
  LocalStorageTemplates._();

  /// pubspec.yaml for the local-storage package.
  ///
  /// [packageName] is the workspace member name, e.g. `myapp_local_storage`.
  /// `resolution: workspace` is required for every member of a Dart workspace.
  static String packagePubspec({required String packageName}) => '''name: $packageName
description: "Offline-first local storage (Drift) — generated by NEAT."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
''';

  /// Public entry point (barrel) of the package.
  static String publicApi({required String packageName}) => '''/// Public API of the $packageName package.
library;

// Phase 2 will export the Drift database and DAOs from here.
export 'src/placeholder.dart';
''';

  /// Phase 1 placeholder so the package has compilable source.
  /// Replaced by the Drift database in Phase 2.
  static String placeholder() => '''/// Placeholder until the Drift database lands (Phase 2).
class LocalStorage {
  const LocalStorage();
}
''';
}
