import 'package:neat/features/generation/domain/models/field_spec.dart';
import 'package:neat/features/generation/domain/services/templates/dart/_template_utils.dart';
import 'package:neat/features/generation/domain/services/templates/dart/field_codegen.dart';

/// Templates for the `<name>_local_storage` workspace package.
///
/// Emits a self-contained Drift package: its own pubspec (`resolution:
/// workspace`), an [AppDatabase] with a typed table for the witness feature
/// (full local CRUD) plus the Outbox queue when sync is enabled, and a public
/// barrel.
class LocalStorageTemplates {
  LocalStorageTemplates._();

  /// pubspec.yaml for the local-storage package.
  ///
  /// [packageName] is the workspace member name, e.g. `myapp_local_storage`.
  /// `resolution: workspace` is required for every member of a Dart workspace.
  static String packagePubspec({required String packageName}) => '''name: $packageName
description: "Offline-first local storage (Drift) — generated by NEAT."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.33.0
  drift_flutter: ^0.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.33.0
''';

  /// Public entry point (barrel) of the package.
  ///
  /// Re-exports the drift runtime so consumers manipulate rows/queries without
  /// declaring a direct dependency on `drift`.
  static String publicApi({required String packageName}) =>
      '''/// Public API of the $packageName package.
library;

export 'package:drift/drift.dart';

export 'src/database.dart';
''';

  /// build_runner config for the package. Turns off drift_dev's fluent
  /// `db.managers.*` API generation — NEAT's own DAOs never use it, and with
  /// zero tables (no first feature yet) the generated `$AppDatabaseManager`
  /// class ends up with an unused field, which fails the analyze gate.
  static String buildYaml() => '''targets:
  \$default:
    builders:
      drift_dev:
        options:
          generate_manager: false
''';

  /// A typed table for [featureName] (columns from the inferred [fields], keyed
  /// on the String id). Reused by the initial database and by feature-gen
  /// injection. The id stays a non-nullable `TextColumn` primary key.
  static String featureTable(String featureName, {List<FieldSpec> fields = FieldSpec.idName}) {
    final p = pascal(featureName);
    final columns = fields.map((f) => '  ${f.driftColumnLine()}').join('\n');
    final pk = idField(fields).dartName;
    return '''/// Typed local table for the $featureName feature (full CRUD).
@DataClassName('${p}Row')
class ${p}Rows extends Table {
$columns

  @override
  Set<Column<Object>> get primaryKey => {$pk};
}''';
  }

  /// The CRUD DAO methods for [featureName]'s table, as a class-body snippet.
  static String featureDao(String featureName) {
    final p = pascal(featureName);
    final acc = '${camel(featureName)}Rows';
    return '''  // ── $featureName CRUD ───────────────────────────────────────────────────────

  Future<List<${p}Row>> getAll${p}s() => select($acc).get();

  Future<${p}Row?> get$p(String id) =>
      (select($acc)..where((t) => t.id.equals(id))).getSingleOrNull();

  /// Reactive list (emits on every local write).
  Stream<List<${p}Row>> watch${p}s() => select($acc).watch();

  Future<void> upsert$p(${p}Row row) => into($acc).insertOnConflictUpdate(row);

  Future<void> upsertAll${p}s(List<${p}Row> rows) =>
      batch((b) => b.insertAllOnConflictUpdate($acc, rows));

  Future<void> delete$p(String id) =>
      (delete($acc)..where((t) => t.id.equals(id))).go();''';
  }

  /// The Drift database. Carries a typed table for the witness [featureName]
  /// (full local CRUD); when [withOutbox] is true it also carries the Outbox
  /// queue table + helpers for the sync strategy. Anchors (`// neat:…`) let
  /// feature-gen inject new tables / DAOs later.
  static String database({
    required String featureName,
    bool withOutbox = false,
    bool includeFirstTable = true,
    List<FieldSpec> fields = FieldSpec.idName,
  }) {
    final p = pascal(featureName);

    final tableEntries = StringBuffer();
    if (includeFirstTable) tableEntries.write('    ${p}Rows,\n');
    if (withOutbox) tableEntries.write('    OutboxEntries,\n');
    tableEntries.write('    // neat:table-names');

    final outboxTable = withOutbox
        ? '''

/// Outbox queue: writes made offline are appended here and replayed by the
/// SyncService when connectivity returns.
class OutboxEntries extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get operation => text()();
  TextColumn get endpoint => text()();
  TextColumn get payload => text().nullable()();
  IntColumn get retryCount => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}'''
        : '';

    final outboxMethods = withOutbox
        ? '''

  // ── Outbox ────────────────────────────────────────────────────────────────

  /// Queue a write to be replayed later.
  Future<void> enqueueOutbox({
    required String operation,
    required String endpoint,
    String? payload,
  }) =>
      into(outboxEntries).insert(OutboxEntriesCompanion.insert(
        operation: operation,
        endpoint: endpoint,
        payload: Value(payload),
      ));

  /// Pending writes, oldest first.
  Future<List<OutboxEntry>> pendingOutbox() =>
      (select(outboxEntries)..orderBy([(t) => OrderingTerm.asc(t.createdAt)])).get();

  /// Watch the pending queue reactively.
  Stream<List<OutboxEntry>> watchPendingOutbox() => select(outboxEntries).watch();

  Future<void> deleteOutbox(int id) =>
      (delete(outboxEntries)..where((t) => t.id.equals(id))).go();

  Future<void> incrementRetry(int id) async {
    final row =
        await (select(outboxEntries)..where((t) => t.id.equals(id))).getSingleOrNull();
    if (row == null) return;
    await (update(outboxEntries)..where((t) => t.id.equals(id)))
        .write(OutboxEntriesCompanion(retryCount: Value(row.retryCount + 1)));
  }'''
        : '';

    final featureTableBlock = includeFirstTable ? featureTable(featureName, fields: fields) : '';

    return '''import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

part 'database.g.dart';

$featureTableBlock$outboxTable

// neat:tables — feature tables are inserted above this line.

@DriftDatabase(
  tables: [
${tableEntries.toString()}
  ],
)
class AppDatabase extends _\$AppDatabase {
  AppDatabase([QueryExecutor? executor]) : super(executor ?? _open());

  @override
  int get schemaVersion => 1;

  // A table added later (Workshop feature-gen) bumps schemaVersion and
  // inserts its own `if (from < N) await m.createTable(...)` step here —
  // otherwise a device that already has the app installed keeps its old
  // on-disk schema forever (Drift only runs onCreate on a brand-new database
  // file, never onUpgrade, unless the version actually changes).
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          // neat:migrations
        },
      );

${includeFirstTable ? featureDao(featureName) : ''}$outboxMethods

  // neat:daos — feature DAOs are inserted above this line.

  static QueryExecutor _open() => driftDatabase(name: 'app_db');
}
''';
  }
}
