import 'package:neat/features/theme_engine/domain/models/theme_engine_state.dart';

class ThemeTemplates {
  ThemeTemplates._();

  // ── constant/constant.dart ────────────────────────────────────────────────

  static String constantBarrel({bool useScreenUtil = false}) {
    final su = useScreenUtil
        ? "import 'package:flutter_screenutil/flutter_screenutil.dart';\n"
        : '';
    return '''import 'package:flutter/material.dart';
$su
part 'app_color.dart';
part 'app_gap.dart';
''';
  }

  // ── constant/app_color.dart ───────────────────────────────────────────────

  static String appColor({
    String seedHex = '0xFF6366F1',
    String accentHex = '0xFF1E293B',
    String errorHex = '0xFFEF4444',
  }) {
    final darkHex = _darkenHex(seedHex, 0.15);
    final subtleHex = _subtleHex(seedHex);
    final errorDimHex = _darkenHex(errorHex, 0.15);
    final errorContainerHex = _subtleHex(errorHex);
    return '''part of 'constant.dart';

class Palette {
  Palette._();

  // ── Primary Brand (generated by NEAT Theme Engine) ─────────────────────────
  static const Color primary = Color($seedHex);
  static const Color primaryDim = Color($darkHex);
  static const Color primaryLight = Color($subtleHex);
  static const Color onPrimary = Color(0xFFFFFFFF);

  // ── Accent (alternate filled — e.g. AppButton "accent" variant) ────────────
  static const Color accent = Color($accentHex);
  static const Color onAccent = Color(0xFFFFFFFF);

  // ── Text / Neutral ───────────────────────────────────────────────────────
  static const Color textPrimary = Color(0xFF121827);
  static const Color textSecondary = Color(0xFF6B7280);
  static const Color textTertiary = Color(0xFFD1D5DB);
  static const Color divider = Color(0xFFE5E7EB);
  static const Color background = Color(0xFFF9FAFB);
  static const Color surface = Color(0xFFFFFFFF);

  // ── Semantic Colors ──────────────────────────────────────────────────────
  static const Color error = Color($errorHex);
  static const Color errorDim = Color($errorDimHex);
  static const Color errorContainer = Color($errorContainerHex);

  static const Color success = Color(0xFF16A34A);
  static const Color successContainer = Color(0x1A16A34A);
  static const Color warning = Color(0xFFD97706);
  static const Color warningContainer = Color(0x1AD97706);
  static const Color info = Color(0xFF3B82F6);
  static const Color infoContainer = Color(0x1A3B82F6);
}
''';
  }

  // ── constant/app_gap.dart ─────────────────────────────────────────────────

  static String appGap({bool useScreenUtil = false}) {
    const sizes = [4, 6, 8, 10, 12, 16, 20, 24, 32, 48, 64];

    final sb = StringBuffer("part of 'constant.dart';\n\nclass Sizes {\n");
    for (final s in sizes) {
      sb.writeln('  static const double p$s = $s;');
    }
    sb.writeln('}\n');

    sb.writeln('// Padding.');
    sb.writeln('extension GapPaddingX on num {');
    if (useScreenUtil) {
      // .w/.h/.sp scale the raw number *before* it's wrapped — applying them
      // to the already-built SizedBox/EdgeInsets instead (as this used to)
      // doesn't compile, since those extensions are declared on num, not on
      // SizedBox/EdgeInsets.
      sb.writeln('SizedBox get gapW => SizedBox(width: toDouble().w);');
      sb.writeln();
      sb.writeln('SizedBox get gapH => SizedBox(height: toDouble().h);');
      sb.writeln();
      sb.writeln('EdgeInsets get pAll => EdgeInsets.all(toDouble().sp);');
      sb.writeln();
      sb.writeln('EdgeInsets get pH => EdgeInsets.symmetric(horizontal: toDouble().w);');
      sb.writeln();
      sb.writeln('EdgeInsets get pV => EdgeInsets.symmetric(vertical: toDouble().h);');
      sb.writeln();
      sb.writeln('double get p => toDouble().sp;');
    } else {
      sb.writeln('SizedBox get gapW => SizedBox(width: toDouble()); ');
      sb.writeln();
      sb.writeln('SizedBox get gapH => SizedBox(height: toDouble());');
      sb.writeln();
      sb.writeln('EdgeInsets get pAll => EdgeInsets.all(toDouble());');
      sb.writeln();
      sb.writeln('EdgeInsets get pH => EdgeInsets.symmetric(horizontal: toDouble());');
      sb.writeln();
      sb.writeln('EdgeInsets get pV => EdgeInsets.symmetric(vertical: toDouble());');
      sb.writeln();
      sb.writeln('double get p => toDouble();');
    }
    sb.writeln('}\n');

    return sb.toString();
  }

  // ── typography/typography.dart ────────────────────────────────────────────

  static String typographyBarrel({required String packageName, bool useScreenUtil = false}) {
    final su = useScreenUtil
        ? "import 'package:flutter_screenutil/flutter_screenutil.dart';\n"
        : '';
    return '''import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
${su}import 'package:$packageName/core/theme/constant/constant.dart';

part 'font_size.dart';
part 'font_weight.dart';
part 'text_style.dart';
''';
  }

  // ── typography/font_size.dart ─────────────────────────────────────────────

  static String fontSize(
    Map<TextStyleKey, TextStyleConfig> textStyles, {
    bool useScreenUtil = false,
  }) {
    // With ScreenUtil, sizes are responsive (.sp) so they can't be const.
    final entries = textStyles.entries
        .map((e) {
          final name = e.key.name;
          final value = e.value.fontSize;
          return useScreenUtil
              ? '  static double get $name => $value.sp;'
              : '  static const double $name = $value;';
        })
        .join('\n');
    return '''part of 'typography.dart';

class FontSizeTheme {
  FontSizeTheme._();

$entries
}
''';
  }

  // ── typography/font_weight.dart ───────────────────────────────────────────

  static String fontWeight(String fontFamily) =>
      '''part of 'typography.dart';

class FontFamilyTheme {
  FontFamilyTheme._();

  static String mainFont = '$fontFamily';
}

class FontWeightTheme {
  FontWeightTheme._();

  static const FontWeight black = FontWeight.w900;
  static const FontWeight extraBold = FontWeight.w800;
  static const FontWeight bold = FontWeight.w700;
  static const FontWeight semiBold = FontWeight.w600;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight regular = FontWeight.w400;
  static const FontWeight light = FontWeight.w300;
  static const FontWeight extraLight = FontWeight.w200;
  static const FontWeight thin = FontWeight.w100;
}
''';

  // ── typography/text_style.dart ────────────────────────────────────────────

  static String textStyle(Map<TextStyleKey, TextStyleConfig> textStyles) {
    final getters = textStyles.entries
        .map((e) {
          final fw = e.value.fontWeight;
          final ls = e.value.letterSpacing.toStringAsFixed(2);
          final h = e.value.height.toStringAsFixed(2);
          return '  static TextStyle get ${e.key.name} =>\n'
              '      _base.copyWith(\n'
              '        fontSize: FontSizeTheme.${e.key.name},\n'
              '        fontWeight: FontWeight.w$fw,\n'
              '        letterSpacing: $ls,\n'
              '        height: $h,\n'
              '      );';
        })
        .join('\n\n');

    return '''part of 'typography.dart';

class StyleTheme {
  StyleTheme._();

  // Resolved via google_fonts so the chosen family is actually applied
  // (downloaded & cached at runtime — no font assets to bundle).
  static TextStyle get _base => GoogleFonts.getFont(
        FontFamilyTheme.mainFont,
        color: Palette.textPrimary,
        fontWeight: FontWeightTheme.regular,
      );

$getters
}
''';
  }

  // ── app_theme_extensions.dart ─────────────────────────────────────────────

  static String appThemeExtensions({required String packageName}) =>
      '''import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';

class AppColors extends ThemeExtension<AppColors> {
  const AppColors({
    required this.primary,
    required this.primaryDim,
    required this.primaryLight,
    required this.success,
    required this.successContainer,
    required this.warning,
    required this.warningContainer,
    required this.error,
    required this.errorContainer,
  });

  final Color primary;
  final Color primaryDim;
  final Color primaryLight;
  final Color success;
  final Color successContainer;
  final Color warning;
  final Color warningContainer;
  final Color error;
  final Color errorContainer;

  static const AppColors light = AppColors(
    primary: Palette.primary,
    primaryDim: Palette.primaryDim,
    primaryLight: Palette.primaryLight,
    success: Palette.success,
    successContainer: Palette.successContainer,
    warning: Palette.warning,
    warningContainer: Palette.warningContainer,
    error: Palette.error,
    errorContainer: Palette.errorContainer,
  );

  @override
  AppColors copyWith({
    Color? primary,
    Color? primaryDim,
    Color? primaryLight,
    Color? success,
    Color? successContainer,
    Color? warning,
    Color? warningContainer,
    Color? error,
    Color? errorContainer,
  }) => AppColors(
    primary: primary ?? this.primary,
    primaryDim: primaryDim ?? this.primaryDim,
    primaryLight: primaryLight ?? this.primaryLight,
    success: success ?? this.success,
    successContainer: successContainer ?? this.successContainer,
    warning: warning ?? this.warning,
    warningContainer: warningContainer ?? this.warningContainer,
    error: error ?? this.error,
    errorContainer: errorContainer ?? this.errorContainer,
  );

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) return this;
    return AppColors(
      primary: Color.lerp(primary, other.primary, t)!,
      primaryDim: Color.lerp(primaryDim, other.primaryDim, t)!,
      primaryLight: Color.lerp(primaryLight, other.primaryLight, t)!,
      success: Color.lerp(success, other.success, t)!,
      successContainer: Color.lerp(successContainer, other.successContainer, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      warningContainer: Color.lerp(warningContainer, other.warningContainer, t)!,
      error: Color.lerp(error, other.error, t)!,
      errorContainer: Color.lerp(errorContainer, other.errorContainer, t)!,
    );
  }
}

extension AppThemeContext on BuildContext {
  AppColors get appColors => Theme.of(this).extension<AppColors>()!;
  TextTheme get textTheme => Theme.of(this).textTheme;
  ColorScheme get colorScheme => Theme.of(this).colorScheme;
}
''';

  // ── components/app_button.dart (opt-in design-system button) ──────────────

  /// A complete design-system button widget, wired to the generated [Palette]
  /// and theme. Variants, sizes, icon, loading, expand and a dashed border.
  static String appButtonComponent({required String packageName}) =>
      '''import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';

enum AppButtonVariant {
  primary,
  destructive,
  secondary,
  accent,
  outlined,
  outlinedDestructive,
  ghost,
  ghostDestructive,
  link,
  linkSecondary,
}

enum AppButtonSize { lg, md, sm }

/// Unified button covering every variant in the design system.
class AppButton extends StatelessWidget {
  const AppButton({
    super.key,
    required this.label,
    this.onPressed,
    this.variant = AppButtonVariant.primary,
    this.size = AppButtonSize.md,
    this.icon,
    this.iconAlignment = IconAlignment.start,
    this.isLoading = false,
    this.expand = false,
    this.dashedBorder = false,
    this.hasError = false,
  });

  final String label;

  /// Null disables the button.
  final VoidCallback? onPressed;

  final AppButtonVariant variant;
  final AppButtonSize size;
  final Widget? icon;
  final IconAlignment iconAlignment;
  final bool isLoading;
  final bool expand;
  final bool dashedBorder;
  final bool hasError;

  EdgeInsetsGeometry get _padding => switch (size) {
        AppButtonSize.sm => const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
        AppButtonSize.lg => const EdgeInsets.symmetric(horizontal: 24, vertical: 22),
        AppButtonSize.md => const EdgeInsets.symmetric(horizontal: 20, vertical: 16.5),
      };

  double get _fontSize => size == AppButtonSize.sm ? 12 : 14;
  double get _radius => size == AppButtonSize.sm ? 8 : 10;
  double get _loaderSize => size == AppButtonSize.sm ? 14 : 18;
  bool get _isDisabled => onPressed == null || isLoading;

  Widget _buildChild(Color contentColor, TextStyle? textStyle) {
    if (isLoading) {
      return SizedBox(
        width: _loaderSize,
        height: _loaderSize,
        child: CircularProgressIndicator(
          strokeWidth: 2,
          valueColor: AlwaysStoppedAnimation<Color>(contentColor),
        ),
      );
    }
    final labelWidget = Text(label, style: textStyle);
    if (icon == null) return labelWidget;
    final iconWidget = IconTheme(
      data: IconThemeData(size: _fontSize + 4, color: contentColor),
      child: icon!,
    );
    final children = iconAlignment == IconAlignment.start
        ? [iconWidget, const SizedBox(width: 8), labelWidget]
        : [labelWidget, const SizedBox(width: 8), iconWidget];
    return Row(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.center,
      children: children,
    );
  }

  @override
  Widget build(BuildContext context) {
    if (dashedBorder) return _DashedButton(button: this);

    final theme = Theme.of(context);
    final onTap = _isDisabled ? null : onPressed;
    final textStyle = theme.textTheme.labelLarge?.copyWith(
      fontSize: _fontSize,
      letterSpacing: 0.5,
      fontWeight: FontWeight.w600,
    );

    // Inline text link.
    if (variant == AppButtonVariant.link || variant == AppButtonVariant.linkSecondary) {
      return TextButton(
        onPressed: onTap,
        style: TextButton.styleFrom(
          padding: EdgeInsets.zero,
          minimumSize: Size.zero,
          tapTargetSize: MaterialTapTargetSize.shrinkWrap,
          foregroundColor: Palette.textPrimary,
          textStyle: textStyle?.copyWith(
            decoration: TextDecoration.underline,
            decorationColor: Palette.textPrimary,
            decorationThickness: 1.5,
          ),
        ),
        child: _buildChild(Palette.textPrimary, null),
      );
    }

    final shape = RoundedRectangleBorder(borderRadius: BorderRadius.circular(_radius));

    Widget styled({
      required Color bg,
      required Color fg,
      Color? border,
    }) {
      final commonStyle = ButtonStyle(
        padding: WidgetStateProperty.all(_padding),
        shape: WidgetStateProperty.all(shape),
        textStyle: WidgetStateProperty.all(textStyle),
        backgroundColor: WidgetStateProperty.resolveWith(
          (s) => s.contains(WidgetState.disabled) ? Palette.divider : bg,
        ),
        foregroundColor: WidgetStateProperty.resolveWith(
          (s) => s.contains(WidgetState.disabled) ? Palette.textSecondary : fg,
        ),
        side: border == null
            ? null
            : WidgetStateProperty.resolveWith(
                (s) => BorderSide(
                  color: s.contains(WidgetState.disabled) ? Palette.divider : border,
                  width: 1.5,
                ),
              ),
        elevation: WidgetStateProperty.all(0.0),
      );
      final isOutlinedOrGhost = bg == Colors.transparent;
      return isOutlinedOrGhost
          ? (border != null
              ? OutlinedButton(onPressed: onTap, style: commonStyle, child: _buildChild(fg, null))
              : TextButton(onPressed: onTap, style: commonStyle, child: _buildChild(fg, null)))
          : FilledButton(onPressed: onTap, style: commonStyle, child: _buildChild(fg, null));
    }

    final button = switch (variant) {
      AppButtonVariant.primary => styled(bg: Palette.primary, fg: Palette.onPrimary),
      AppButtonVariant.destructive => styled(bg: Palette.error, fg: Palette.surface),
      AppButtonVariant.secondary =>
        styled(bg: Palette.surface, fg: Palette.textPrimary, border: Palette.divider),
      AppButtonVariant.accent => styled(bg: Palette.accent, fg: Palette.onAccent),
      AppButtonVariant.outlined =>
        styled(bg: Colors.transparent, fg: Palette.primary, border: Palette.primary),
      AppButtonVariant.outlinedDestructive =>
        styled(bg: Colors.transparent, fg: Palette.error, border: Palette.error),
      AppButtonVariant.ghost => styled(bg: Colors.transparent, fg: Palette.primary),
      AppButtonVariant.ghostDestructive => styled(bg: Colors.transparent, fg: Palette.error),
      AppButtonVariant.link || AppButtonVariant.linkSecondary => const SizedBox.shrink(),
    };

    return expand ? SizedBox(width: double.infinity, child: button) : button;
  }
}

// ── Dashed border button ──────────────────────────────────────────────────────

class _DashedButton extends StatelessWidget {
  const _DashedButton({required this.button});

  final AppButton button;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final disabled = button._isDisabled;
    final textColor = disabled ? Palette.textSecondary : Palette.textPrimary;
    final borderColor = disabled
        ? Palette.divider
        : button.hasError
            ? Palette.error
            : Palette.primary;

    final textStyle = theme.textTheme.labelLarge?.copyWith(
      color: textColor,
      fontSize: button._fontSize,
      letterSpacing: 0.5,
      fontWeight: FontWeight.w600,
    );

    final content = button.expand
        ? SizedBox(
            width: double.infinity,
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
              child: Center(child: button._buildChild(textColor, textStyle)),
            ),
          )
        : Padding(padding: button._padding, child: button._buildChild(textColor, textStyle));

    return GestureDetector(
      onTap: disabled ? null : button.onPressed,
      child: CustomPaint(
        painter: _DashedBorderPainter(color: borderColor, radius: button._radius),
        child: content,
      ),
    );
  }
}

class _DashedBorderPainter extends CustomPainter {
  const _DashedBorderPainter({required this.color, required this.radius});

  final Color color;
  final double radius;

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color
      ..strokeWidth = 1.5
      ..style = PaintingStyle.stroke;
    final path = Path()
      ..addRRect(
        RRect.fromRectAndRadius(
          Rect.fromLTWH(0.75, 0.75, size.width - 1.5, size.height - 1.5),
          Radius.circular(radius),
        ),
      );
    const dashWidth = 6.0;
    const dashGap = 2.0;
    for (final metric in path.computeMetrics()) {
      var distance = 0.0;
      while (distance < metric.length) {
        canvas.drawPath(metric.extractPath(distance, distance + dashWidth), paint);
        distance += dashWidth + dashGap;
      }
    }
  }

  @override
  bool shouldRepaint(_DashedBorderPainter old) => old.color != color;
}
''';

  // ── components/app_card.dart ──────────────────────────────────────────────

  static String appCardComponent({required String packageName}) =>
      '''import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';

/// A standardized surface card: padding, rounded corners, optional tap & shadow.
class AppCard extends StatelessWidget {
  const AppCard({
    required this.child,
    super.key,
    this.padding = const EdgeInsets.all(16),
    this.margin,
    this.onTap,
    this.color,
    this.borderRadius,
    this.hasShadow = false,
    this.hasBorder = true,
  });

  final Widget child;
  final EdgeInsetsGeometry padding;
  final EdgeInsetsGeometry? margin;
  final VoidCallback? onTap;
  final Color? color;
  final BorderRadius? borderRadius;
  final bool hasShadow;
  final bool hasBorder;

  @override
  Widget build(BuildContext context) {
    final radius = borderRadius ?? BorderRadius.circular(12);

    Widget content = Padding(padding: padding, child: child);
    if (onTap != null) {
      content = InkWell(borderRadius: radius, onTap: onTap, child: content);
    }

    return Container(
      margin: margin,
      decoration: BoxDecoration(
        color: color ?? Palette.surface,
        borderRadius: radius,
        border: hasBorder ? Border.all(color: Palette.divider) : null,
        boxShadow: hasShadow
            ? [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.06),
                  blurRadius: 8,
                  offset: const Offset(0, 2),
                ),
              ]
            : null,
      ),
      clipBehavior: Clip.antiAlias,
      child: content,
    );
  }
}
''';

  // ── components/app_text_field.dart ────────────────────────────────────────

  static String appTextFieldComponent({required String packageName}) =>
      '''import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:$packageName/core/theme/constant/constant.dart';

/// Generic text field: optional label above, error message below, and an
/// automatic password visibility toggle when [obscureText] is true.
class AppTextField extends StatefulWidget {
  const AppTextField({
    super.key,
    this.label,
    this.hint,
    this.controller,
    this.focusNode,
    this.obscureText = false,
    this.keyboardType,
    this.textInputAction,
    this.errorText,
    this.onChanged,
    this.onSubmitted,
    this.enabled = true,
    this.prefixIcon,
    this.suffixIcon,
    this.inputFormatters,
    this.autofocus = false,
    this.readOnly = false,
    this.maxLines = 1,
    this.minLines,
  });

  final String? label;
  final String? hint;
  final TextEditingController? controller;
  final FocusNode? focusNode;
  final bool obscureText;
  final TextInputType? keyboardType;
  final TextInputAction? textInputAction;
  final String? errorText;
  final ValueChanged<String>? onChanged;
  final ValueChanged<String>? onSubmitted;
  final bool enabled;
  final Widget? prefixIcon;
  final Widget? suffixIcon;
  final List<TextInputFormatter>? inputFormatters;
  final bool autofocus;
  final bool readOnly;
  final int? maxLines;
  final int? minLines;

  @override
  State<AppTextField> createState() => _AppTextFieldState();
}

class _AppTextFieldState extends State<AppTextField> {
  late bool _obscured;

  @override
  void initState() {
    super.initState();
    _obscured = widget.obscureText;
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final hasError = widget.errorText != null && widget.errorText!.isNotEmpty;

    Widget? suffix = widget.suffixIcon;
    if (suffix == null && widget.obscureText) {
      suffix = IconButton(
        icon: Icon(
          _obscured ? Icons.visibility_outlined : Icons.visibility_off_outlined,
          color: Palette.textSecondary,
          size: 20,
        ),
        onPressed: () => setState(() => _obscured = !_obscured),
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        if (widget.label != null) ...[
          Text(
            widget.label!,
            style: theme.textTheme.titleSmall?.copyWith(
              fontWeight: FontWeight.w600,
              color: Palette.textPrimary,
            ),
          ),
          const SizedBox(height: 6),
        ],
        TextField(
          controller: widget.controller,
          focusNode: widget.focusNode,
          obscureText: _obscured,
          keyboardType: widget.keyboardType,
          textInputAction: widget.textInputAction,
          onChanged: widget.onChanged,
          onSubmitted: widget.onSubmitted,
          enabled: widget.enabled,
          inputFormatters: widget.inputFormatters,
          autofocus: widget.autofocus,
          readOnly: widget.readOnly,
          maxLines: widget.obscureText ? 1 : widget.maxLines,
          minLines: widget.minLines,
          style: theme.textTheme.bodyLarge,
          decoration: InputDecoration(
            hintText: widget.hint,
            prefixIcon: widget.prefixIcon,
            suffixIcon: suffix,
            enabledBorder: hasError
                ? OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: const BorderSide(color: Palette.error, width: 1.5),
                  )
                : null,
          ),
        ),
        if (hasError) ...[
          const SizedBox(height: 4),
          Text(
            widget.errorText!,
            style: theme.textTheme.bodySmall?.copyWith(color: Palette.error),
          ),
        ],
      ],
    );
  }
}
''';

  // ── widgetbook/main.dart (opt-in catalog) ─────────────────────────────────

  /// Scaffolds a Widgetbook catalog for the enabled [components].
  /// Lives outside lib/ — run with `flutter run -t widgetbook/main.dart`.
  static String widgetbookApp({
    required String packageName,
    required Set<AppComponent> components,
  }) {
    final imports = <String>[
      "import 'package:flutter/material.dart';",
      "import 'package:widgetbook/widgetbook.dart';",
      "import 'package:$packageName/core/theme/app_theme.dart';",
      for (final c in components) "import 'package:$packageName/components/${c.fileName}';",
    ].join('\n');

    final entries = components.map(_widgetbookEntry).join('\n');

    return '''$imports

void main() => runApp(const WidgetbookApp());

class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      addons: [
        ThemeAddon<ThemeData>(
          themes: [
            WidgetbookTheme(name: 'Light', data: AppTheme.light),
            WidgetbookTheme(name: 'Dark', data: AppTheme.dark),
          ],
          themeBuilder: (context, theme, child) => Theme(data: theme, child: child),
        ),
        TextScaleAddon(),
      ],
      directories: [
$entries
      ],
    );
  }
}
''';
  }

  static String _widgetbookEntry(AppComponent c) {
    switch (c) {
      case AppComponent.button:
        return '''        WidgetbookComponent(
          name: 'AppButton',
          useCases: [
            WidgetbookUseCase(
              name: 'Playground',
              builder: (context) => Center(
                child: AppButton(
                  label: context.knobs.string(label: 'Label', initialValue: 'Button'),
                  variant: context.knobs.object.dropdown(
                    label: 'Variant',
                    options: AppButtonVariant.values,
                    labelBuilder: (v) => v.name,
                  ),
                  size: context.knobs.object.dropdown(
                    label: 'Size',
                    options: AppButtonSize.values,
                    labelBuilder: (v) => v.name,
                  ),
                  isLoading: context.knobs.boolean(label: 'Loading'),
                  expand: context.knobs.boolean(label: 'Expand'),
                  onPressed: () {},
                ),
              ),
            ),
          ],
        ),''';
      case AppComponent.card:
        return '''        WidgetbookComponent(
          name: 'AppCard',
          useCases: [
            WidgetbookUseCase(
              name: 'Default',
              builder: (context) => Center(
                child: Padding(
                  padding: const EdgeInsets.all(24),
                  child: AppCard(
                    hasShadow: context.knobs.boolean(label: 'Shadow'),
                    hasBorder: context.knobs.boolean(label: 'Border', initialValue: true),
                    child: const Text('Card content'),
                  ),
                ),
              ),
            ),
          ],
        ),''';
      case AppComponent.textField:
        return '''        WidgetbookComponent(
          name: 'AppTextField',
          useCases: [
            WidgetbookUseCase(
              name: 'Default',
              builder: (context) => Padding(
                padding: const EdgeInsets.all(24),
                child: AppTextField(
                  label: context.knobs.stringOrNull(label: 'Label', initialValue: 'Email'),
                  hint: context.knobs.string(label: 'Hint', initialValue: 'you@example.com'),
                  obscureText: context.knobs.boolean(label: 'Obscure'),
                  errorText: context.knobs.stringOrNull(label: 'Error'),
                ),
              ),
            ),
          ],
        ),''';
    }
  }

  // ── widgets/asset_images.dart (svg + image helpers in the UI package) ─────

  /// Typed helpers to render SVG / raster assets that ship **inside** the
  /// `<app>_ui` package (so features reference shared branding without copying
  /// files). Assets live under `packages/<ui>/assets/` and are loaded with the
  /// `package:` parameter automatically.
  static String assetWidgets({required String packageName}) =>
      '''import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

/// Renders an SVG asset shipped inside the `$packageName` package.
class SvgPictureCustom extends StatelessWidget {
  const SvgPictureCustom({
    super.key,
    required this.path,
    this.width,
    this.height,
    this.fit,
    this.colorFilter,
    this.semanticsLabel,
  });

  final String path;
  final double? width;
  final double? height;
  final BoxFit? fit;
  final ColorFilter? colorFilter;
  final String? semanticsLabel;

  @override
  Widget build(BuildContext context) {
    return SvgPicture.asset(
      path,
      package: '$packageName',
      width: width,
      height: height,
      fit: fit ?? BoxFit.contain,
      colorFilter: colorFilter,
      semanticsLabel: semanticsLabel,
    );
  }
}

/// Renders a raster image asset shipped inside the `$packageName` package.
class ImagePictureCustom extends StatelessWidget {
  const ImagePictureCustom({
    super.key,
    required this.path,
    this.width,
    this.height,
    this.fit,
  });

  final String path;
  final double? width;
  final double? height;
  final BoxFit? fit;

  @override
  Widget build(BuildContext context) {
    return Image.asset(
      path,
      package: '$packageName',
      width: width,
      height: height,
      fit: fit ?? BoxFit.contain,
    );
  }
}
''';

  // ── spider (typed asset paths) ────────────────────────────────────────────

  /// `spider.yaml` — regenerates typed `Assets.*` constants from `assets/`.
  static String spiderConfig() => '''# Typed asset paths for the design system.
# After adding files under assets/, regenerate with:
#   dart run spider build
export: true
use_part_of: false
no_comments: false

groups:
  - path: assets
    class_name: Assets
    package: gen
    types:
      - .png
      - .jpg
      - .jpeg
      - .webp
      - .gif
      - .svg
''';

  /// `lib/gen/assets.dart` — typed asset path constants (spider-compatible).
  /// NEAT generates it directly so it always compiles + is exported; running
  /// `dart run spider build` regenerates it as assets are added.
  static String assetsClass({required bool hasLogo}) {
    final logo = hasLogo
        ? '\n  /// Uploaded branding logo (also used for app icon + splash).\n'
              "  static const String brandingLogo = 'assets/branding/logo.png';\n"
        : '';
    return '''// GENERATED by NEAT (spider-compatible). Pass these to SvgPictureCustom /
// ImagePictureCustom. Regenerate after adding assets: `dart run spider build`.
class Assets {
  Assets._();
$logo}
''';
  }

  // ── app_theme.dart (from the live ThemeEngineState) ───────────────────────

  /// Single source of truth for generating `app_theme.dart` from the current
  /// [ThemeEngineState]. Used by BOTH the live code preview and the generator,
  /// so what the user sees is exactly what gets written.
  static String appThemeForState({
    required ThemeEngineState theme,
    required String packageName,
    bool forceFlex = false,
    bool useScreenUtil = false,
  }) {
    final useFlex = forceFlex || theme.approach == ThemeApproach.flexColorScheme;
    if (useFlex) {
      return appThemeFlexColorScheme(
        packageName: packageName,
        customCode: theme.flexColorSchemeCode,
        textStyles: theme.textStyles,
      );
    }
    return appThemeBasic(
      packageName: packageName,
      containerRadius: theme.containerRadius,
      cardElevation: theme.cardElevation,
      textStyles: theme.textStyles,
      elevatedRadius: theme.effectiveRadius(theme.elevatedButton),
      elevatedHPad: theme.elevatedButton.hPadding,
      elevatedVPad: theme.elevatedButton.vPadding,
      elevatedElevation: theme.elevatedButton.elevation ?? 4,
      filledRadius: theme.effectiveRadius(theme.filledButton),
      filledHPad: theme.filledButton.hPadding,
      filledVPad: theme.filledButton.vPadding,
      outlinedRadius: theme.effectiveRadius(theme.outlinedButton),
      outlinedHPad: theme.outlinedButton.hPadding,
      outlinedVPad: theme.outlinedButton.vPadding,
      outlinedStroke: theme.outlinedButton.strokeWidth ?? 1.5,
      textRadius: theme.effectiveRadius(theme.textButton),
      textHPad: theme.textButton.hPadding,
      textVPad: theme.textButton.vPadding,
      primaryOverrideHex: theme.primaryOverrideHex,
      secondaryOverrideHex: theme.secondaryOverrideHex,
      tertiaryOverrideHex: theme.tertiaryOverrideHex,
      useScreenUtil: useScreenUtil,
    );
  }

  // ── app_theme.dart (basic ThemeData) ──────────────────────────────────────

  static String appThemeBasic({
    required String packageName,
    double containerRadius = 12.0,
    double cardElevation = 0.0,
    // Elevated button
    double elevatedRadius = 12.0,
    double elevatedHPad = 24,
    double elevatedVPad = 12,
    double elevatedElevation = 4,
    // Filled button
    double filledRadius = 12.0,
    double filledHPad = 24,
    double filledVPad = 12,
    // Outlined button
    double outlinedRadius = 12.0,
    double outlinedHPad = 24,
    double outlinedVPad = 12,
    double outlinedStroke = 1.5,
    // Text button
    double textRadius = 12.0,
    double textHPad = 16,
    double textVPad = 8,
    // Typography
    Map<TextStyleKey, TextStyleConfig> textStyles = kM3Defaults,
    // ColorScheme overrides (hex like '0xFF...'), null = keep seed-derived
    String? primaryOverrideHex,
    String? secondaryOverrideHex,
    String? tertiaryOverrideHex,
    // Responsive font sizes via flutter_screenutil (.sp)
    bool useScreenUtil = false,
  }) {
    // Hardcoded font sizes become responsive (.sp) when ScreenUtil is on,
    // which also forces the TextStyle to be non-const.
    final fs = useScreenUtil ? '.sp' : '';
    final tsConst = useScreenUtil ? '' : 'const ';
    // Responsive paddings: horizontal → .w, vertical → .h (drop const via tsConst).
    final pw = useScreenUtil ? '.w' : '';
    final ph = useScreenUtil ? '.h' : '';
    final suImport = useScreenUtil
        ? "import 'package:flutter_screenutil/flutter_screenutil.dart';\n"
        : '';
    final cr = containerRadius.toStringAsFixed(1);
    final el = cardElevation.toStringAsFixed(1);
    // Button radius helpers
    final erStr = elevatedRadius.toStringAsFixed(1);
    final frStr = filledRadius.toStringAsFixed(1);
    final orStr = outlinedRadius.toStringAsFixed(1);
    final trStr = textRadius.toStringAsFixed(1);
    // Padding helpers
    final eHP = elevatedHPad.round();
    final eVP = elevatedVPad.round();
    final fHP = filledHPad.round();
    final fVP = filledVPad.round();
    final oHP = outlinedHPad.round();
    final oVP = outlinedVPad.round();
    final tHP = textHPad.round();
    final tVP = textVPad.round();
    final eEl = elevatedElevation.toStringAsFixed(1);
    final oSt = outlinedStroke.toStringAsFixed(1);

    // Build TextTheme entries only for configured styles
    final textThemeEntries = textStyles.keys
        .map((k) {
          return '      ${k.name}: StyleTheme.${k.name},';
        })
        .join('\n');

    // AppBar uses titleLarge if configured, else falls back gracefully
    final hasTitle = textStyles.containsKey(TextStyleKey.titleLarge);

    // Build a `.copyWith(...)` chained on ColorScheme.fromSeed when the user
    // overrode primary/secondary/tertiary in the Colors tab. Applied to both
    // brightnesses so the generated theme matches the live preview.
    final overrideEntries = [
      if (primaryOverrideHex != null) '      primary: Color($primaryOverrideHex),',
      if (secondaryOverrideHex != null) '      secondary: Color($secondaryOverrideHex),',
      if (tertiaryOverrideHex != null) '      tertiary: Color($tertiaryOverrideHex),',
    ].join('\n');
    final schemeOverride = overrideEntries.isEmpty ? '' : '.copyWith(\n$overrideEntries\n    )';

    return '''import 'package:flutter/material.dart';
${suImport}import 'package:$packageName/core/theme/constant/constant.dart';
import 'package:$packageName/core/theme/typography/typography.dart';
import 'app_theme_extensions.dart';

class AppTheme {
  AppTheme._();

  static ThemeData get light => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: Palette.primary,
      brightness: Brightness.light,
    )$schemeOverride,
    extensions: const [AppColors.light],
    textTheme: TextTheme(
$textThemeEntries
    ),
    scaffoldBackgroundColor: Palette.background,
    appBarTheme: AppBarTheme(
      backgroundColor: Palette.surface,
      foregroundColor: Palette.textPrimary,
      elevation: 0,
      shadowColor: Colors.transparent,
      surfaceTintColor: Colors.transparent,
      ${hasTitle ? 'titleTextStyle: StyleTheme.titleLarge.copyWith(color: Palette.textPrimary),' : ''}
    ),
    cardTheme: CardThemeData(
      color: Palette.surface,
      elevation: $el,
      shadowColor: Colors.black,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular($cr),
        side: BorderSide(color: $el > 0 ? Colors.transparent : Palette.divider),
      ),
      margin: EdgeInsets.zero,
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        elevation: $eEl,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($erStr)),
        textStyle: ${tsConst}TextStyle(fontWeight: FontWeight.w600, fontSize: 14$fs),
        padding: ${tsConst}EdgeInsets.symmetric(horizontal: $eHP$pw, vertical: $eVP$ph),
      ),
    ),
    filledButtonTheme: FilledButtonThemeData(
      style: FilledButton.styleFrom(
        backgroundColor: Palette.primary,
        foregroundColor: Palette.onPrimary,
        elevation: 0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($frStr)),
        textStyle: ${tsConst}TextStyle(fontWeight: FontWeight.w600, fontSize: 14$fs),
        padding: ${tsConst}EdgeInsets.symmetric(horizontal: $fHP$pw, vertical: $fVP$ph),
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        foregroundColor: Palette.primary,
        side: const BorderSide(color: Palette.primary, width: $oSt),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($orStr)),
        textStyle: ${tsConst}TextStyle(fontWeight: FontWeight.w600, fontSize: 14$fs),
        padding: ${tsConst}EdgeInsets.symmetric(horizontal: $oHP$pw, vertical: $oVP$ph),
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        foregroundColor: Palette.primary,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($trStr)),
        textStyle: ${tsConst}TextStyle(fontWeight: FontWeight.w600, fontSize: 14$fs),
        padding: ${tsConst}EdgeInsets.symmetric(horizontal: $tHP$pw, vertical: $tVP$ph),
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: Palette.surface,
      contentPadding: ${tsConst}EdgeInsets.symmetric(horizontal: 16$pw, vertical: 14$ph),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.divider),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.divider),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.primary, width: 1.5),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.error),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular($orStr),
        borderSide: const BorderSide(color: Palette.error, width: 1.5),
      ),
      hintStyle: ${tsConst}TextStyle(color: Palette.textSecondary, fontSize: 14$fs),
      errorStyle: ${tsConst}TextStyle(color: Palette.error, fontSize: 12$fs),
    ),
    dividerTheme: const DividerThemeData(color: Palette.divider, thickness: 1, space: 1),
    dialogTheme: DialogThemeData(
      backgroundColor: Palette.surface,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($cr)),
    ),
    snackBarTheme: SnackBarThemeData(
      backgroundColor: Palette.textPrimary,
      contentTextStyle: ${tsConst}TextStyle(color: Palette.surface, fontSize: 14$fs),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($orStr)),
      behavior: SnackBarBehavior.floating,
    ),
  );

  static ThemeData get dark {
    final scheme = ColorScheme.fromSeed(
      seedColor: Palette.primary,
      brightness: Brightness.dark,
    )$schemeOverride;
    return light.copyWith(
      colorScheme: scheme,
      extensions: const [AppColors.light],
      scaffoldBackgroundColor: scheme.surface,
      // Re-color the text for dark surfaces (the light textTheme bakes in dark colors).
      textTheme: light.textTheme.apply(
        bodyColor: scheme.onSurface,
        displayColor: scheme.onSurface,
      ),
      appBarTheme: light.appBarTheme.copyWith(
        backgroundColor: scheme.surface,
        foregroundColor: scheme.onSurface,
        titleTextStyle: StyleTheme.titleLarge.copyWith(color: scheme.onSurface),
      ),
      cardTheme: light.cardTheme.copyWith(color: scheme.surfaceContainerHighest),
      inputDecorationTheme: light.inputDecorationTheme.copyWith(
        fillColor: scheme.surfaceContainerHighest,
      ),
      dialogTheme: light.dialogTheme.copyWith(backgroundColor: scheme.surface),
      snackBarTheme: light.snackBarTheme.copyWith(
        backgroundColor: scheme.onSurface,
        contentTextStyle: StyleTheme.bodyMedium.copyWith(color: scheme.surface),
      ),
    );
  }
}
''';
  }

  // ── app_theme.dart (flex_color_scheme variant) ────────────────────────────

  /// Generates [app_theme.dart] for the FlexColorScheme approach.
  ///
  /// [customCode] is whatever the user pasted from the FlexColorScheme
  /// playground — a bare `FlexThemeData.light(...)` call, a `theme:`/
  /// `darkTheme:` snippet, or a full file with imports and a wrapper class.
  /// Only the `FlexThemeData.light(...)`/`.dark(...)` (or the older
  /// `FlexColorScheme.light(...).toTheme` equivalent) call **expressions**
  /// are extracted via paren-matching — everything else (imports, wrapper
  /// class/field names, comments) is ignored, so paste shape never matters
  /// and `AppTheme.light`/`.dark` (what `app.dart` actually references) are
  /// always defined correctly. A `dark` config is optional — light is
  /// derived from it when absent. `null` / empty yields a Material Baseline
  /// default.
  static String appThemeFlexColorScheme({
    required String packageName,
    String? customCode,
    Map<TextStyleKey, TextStyleConfig> textStyles = kM3Defaults,
  }) {
    final code = customCode?.trim() ?? '';
    final textThemeEntries = textStyles.keys
        .map((k) => '    ${k.name}: StyleTheme.${k.name},')
        .join('\n');

    final light = _extractFlexCall(code, 'light');
    final dark = _extractFlexCall(code, 'dark');

    final bodyConfig = light != null
        ? '  static ThemeData get light => ${_themeExpr(light)}.copyWith(\n'
              '    textTheme: _textTheme,\n'
              '    extensions: const [AppColors.light],\n'
              '    scaffoldBackgroundColor: Palette.background,\n'
              '  );\n\n'
              '${dark != null ? '  static ThemeData get dark => ${_themeExpr(dark)}.copyWith(\n'
                  '    textTheme: _textTheme,\n'
                  '    extensions: const [AppColors.light],\n'
                  '  );' : '  // Only a light config was pasted — dark is derived from it.\n'
                  '  static ThemeData get dark => light.copyWith(\n'
                  '    extensions: const [AppColors.light],\n'
                  '  );'}'
        : '  static ThemeData get light => FlexThemeData.light(\n'
              '    scheme: FlexScheme.materialBaseline,\n'
              '    subThemesData: const FlexSubThemesData(\n'
              '      interactionEffects: true,\n'
              '      tintedDisabledControls: true,\n'
              '      useM2StyleDividerInM3: true,\n'
              '      inputDecoratorIsFilled: true,\n'
              '      inputDecoratorBorderType: FlexInputBorderType.outline,\n'
              '      alignedDropdown: true,\n'
              '    ),\n'
              '    visualDensity: FlexColorScheme.comfortablePlatformDensity,\n'
              '    useMaterial3: true,\n'
              '    extensions: const [AppColors.light],\n'
              '  ).copyWith(\n'
              '    textTheme: _textTheme,\n'
              '    scaffoldBackgroundColor: Palette.background,\n'
              '  );\n\n'
              '  static ThemeData get dark => FlexThemeData.dark(\n'
              '    scheme: FlexScheme.materialBaseline,\n'
              '    subThemesData: const FlexSubThemesData(\n'
              '      interactionEffects: true,\n'
              '      tintedDisabledControls: true,\n'
              '      blendOnColors: true,\n'
              '      useM2StyleDividerInM3: true,\n'
              '      inputDecoratorIsFilled: true,\n'
              '      inputDecoratorBorderType: FlexInputBorderType.outline,\n'
              '      alignedDropdown: true,\n'
              '    ),\n'
              '    visualDensity: FlexColorScheme.comfortablePlatformDensity,\n'
              '    useMaterial3: true,\n'
              '    extensions: const [AppColors.light],\n'
              '  ).copyWith(\n'
              '    textTheme: _textTheme,\n'
              '  );';

    return '''import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:$packageName/core/theme/constant/constant.dart';
import 'package:$packageName/core/theme/typography/typography.dart';
import 'app_theme_extensions.dart';

class AppTheme {
  AppTheme._();

$bodyConfig

  static TextTheme get _textTheme => TextTheme(
$textThemeEntries
  );
}
''';
  }

  // ── theme_mode_controller.dart (riverpod with annotations) ───────────────

  static String themeModeControllerRiverpod({required String packageName}) =>
      '''import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:flutter/material.dart';

part 'theme_mode_controller.g.dart';

@Riverpod(keepAlive: true)
class ThemeModeController extends _\$ThemeModeController {
  @override
  ThemeMode build() => ThemeMode.light;

  void toggle() => state = state == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;

  void setLight() => state = ThemeMode.light;
  void setDark() => state = ThemeMode.dark;
  void setSystem() => state = ThemeMode.system;
}
''';

  // ── theme_mode_controller.dart (riverpod manual) ──────────────────────────

  static String themeModeControllerRiverpodManual() =>
      r'''import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/material.dart';

final themeModeControllerProvider =
    NotifierProvider<ThemeModeController, ThemeMode>(ThemeModeController.new);

class ThemeModeController extends Notifier<ThemeMode> {
  @override
  ThemeMode build() => ThemeMode.light;

  void toggle() => state = state == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;
  void setLight() => state = ThemeMode.light;
  void setDark() => state = ThemeMode.dark;
  void setSystem() => state = ThemeMode.system;
}
''';

  // ── brightness_theme/brightness_cubit.dart ────────────────────────────────

  static String brightnessCubit() => r'''import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'brightness_state.dart';

class BrightnessCubit extends Cubit<BrightnessState> {
  BrightnessCubit() : super(const BrightnessLight());

  ThemeMode get themeMode =>
      state is BrightnessDark ? ThemeMode.dark : ThemeMode.light;

  void toggle() => state is BrightnessLight
      ? emit(const BrightnessDark())
      : emit(const BrightnessLight());

  void setLight() => emit(const BrightnessLight());
  void setDark() => emit(const BrightnessDark());
}
''';

  static String brightnessCubitState() => r'''part of 'brightness_cubit.dart';

sealed class BrightnessState {
  const BrightnessState();
}

final class BrightnessLight extends BrightnessState {
  const BrightnessLight();
}

final class BrightnessDark extends BrightnessState {
  const BrightnessDark();
}
''';

  // ── brightness_theme/brightness_bloc.dart ────────────────────────────────

  static String brightnessBloc() => r'''import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'brightness_event.dart';
part 'brightness_state.dart';

class BrightnessBloc extends Bloc<BrightnessEvent, BrightnessState> {
  BrightnessBloc() : super(const BrightnessLight()) {
    on<BrightnessToggled>(_onToggled);
    on<BrightnessSetLight>(_onSetLight);
    on<BrightnessSetDark>(_onSetDark);
  }

  ThemeMode get themeMode =>
      state is BrightnessDark ? ThemeMode.dark : ThemeMode.light;

  void _onToggled(BrightnessToggled event, Emitter<BrightnessState> emit) =>
      emit(state is BrightnessLight ? const BrightnessDark() : const BrightnessLight());

  void _onSetLight(BrightnessSetLight event, Emitter<BrightnessState> emit) =>
      emit(const BrightnessLight());

  void _onSetDark(BrightnessSetDark event, Emitter<BrightnessState> emit) =>
      emit(const BrightnessDark());
}
''';

  static String brightnessBlocEvent() => r'''part of 'brightness_bloc.dart';

sealed class BrightnessEvent {
  const BrightnessEvent();
}

final class BrightnessToggled extends BrightnessEvent {
  const BrightnessToggled();
}

final class BrightnessSetLight extends BrightnessEvent {
  const BrightnessSetLight();
}

final class BrightnessSetDark extends BrightnessEvent {
  const BrightnessSetDark();
}
''';

  static String brightnessBlocState() => r'''part of 'brightness_bloc.dart';

sealed class BrightnessState {
  const BrightnessState();
}

final class BrightnessLight extends BrightnessState {
  const BrightnessLight();
}

final class BrightnessDark extends BrightnessState {
  const BrightnessDark();
}
''';

  // ── Private flex injection helpers ───────────────────────────────────────

  /// Returns the index of the `)` that closes the `(` at [openIdx].
  /// Returns -1 if no matching paren is found.
  static int _findMatchingParen(String code, int openIdx) {
    var depth = 0;
    for (var i = openIdx; i < code.length; i++) {
      if (code[i] == '(') depth++;
      if (code[i] == ')') {
        depth--;
        if (depth == 0) return i;
      }
    }
    return -1;
  }

  /// A `FlexThemeData.light(...)` / `.dark(...)` call expression pulled out of
  /// a pasted blob, plus whether it needs `.toTheme` appended (the older
  /// `FlexColorScheme.light(...)` API returns a config object, not a
  /// [ThemeData], unlike `FlexThemeData.light(...)`).
  static ({String expr, bool needsToTheme})? _extractFlexCall(String code, String variant) {
    for (final prefix in ['FlexThemeData.$variant(', 'FlexColorScheme.$variant(']) {
      final callIdx = code.indexOf(prefix);
      if (callIdx == -1) continue;
      final openParen = callIdx + prefix.length - 1;
      final closeParen = _findMatchingParen(code, openParen);
      if (closeParen == -1) continue;
      return (
        expr: code.substring(callIdx, closeParen + 1),
        needsToTheme: prefix.startsWith('FlexColorScheme'),
      );
    }
    return null;
  }

  static String _themeExpr(({String expr, bool needsToTheme}) call) =>
      call.needsToTheme ? '(${call.expr}).toTheme' : call.expr;

  // ── Private hex helpers ───────────────────────────────────────────────────

  /// Darkens an ARGB hex string like '0xFF00DCE5' by [factor] (0.0–1.0).
  static String _darkenHex(String hexARGB, double factor) {
    final v = int.parse(hexARGB.replaceFirst('0x', ''), radix: 16);
    final a = (v >> 24) & 0xFF;
    var r = (v >> 16) & 0xFF;
    var g = (v >> 8) & 0xFF;
    var b = v & 0xFF;
    r = (r * (1 - factor)).round().clamp(0, 255);
    g = (g * (1 - factor)).round().clamp(0, 255);
    b = (b * (1 - factor)).round().clamp(0, 255);
    final result = (a << 24) | (r << 16) | (g << 8) | b;
    return '0x${result.toRadixString(16).padLeft(8, '0').toUpperCase()}';
  }

  /// Returns a low-opacity (10%) version of [hexARGB] for subtle backgrounds.
  static String _subtleHex(String hexARGB) {
    final v = int.parse(hexARGB.replaceFirst('0x', ''), radix: 16);
    final r = (v >> 16) & 0xFF;
    final g = (v >> 8) & 0xFF;
    final b = v & 0xFF;
    // alpha = 0x1A ≈ 10%
    const a = 0x1A;
    final result = (a << 24) | (r << 16) | (g << 8) | b;
    return '0x${result.toRadixString(16).padLeft(8, '0').toUpperCase()}';
  }
}
