import 'dart:io';

import 'package:neat/features/generation/domain/usecases/writers/generation_io.dart';
import 'package:neat/features/theme_engine/domain/models/theme_engine_state.dart';
import 'package:neat/features/theme_engine/domain/services/theme_templates.dart';

/// Writes the extracted `<app>_ui` workspace package (theme + tokens +
/// components) and the standalone Widgetbook member's pubspec — split out of
/// `LaunchGenerationUsecase` (see ROADMAP.md for the per-domain writer split).
abstract final class UiPackageWriter {
  static Future<void> write(
    Directory projectDir,
    String uiPackage, {
    required Set<AppComponent> components,
    required bool useScreenUtil,
    String? flexVersion,
    String logoPath = '',
  }) async {
    final root = '${projectDir.path}/packages/$uiPackage';

    final deps = StringBuffer()
      ..writeln('  flutter:')
      ..writeln('    sdk: flutter')
      ..writeln('  google_fonts: ^8.1.0')
      ..writeln('  flutter_svg: ^2.0.16');
    if (useScreenUtil) deps.writeln('  flutter_screenutil: ^5.9.3');
    if (flexVersion != null) deps.writeln('  flex_color_scheme: ^$flexVersion');

    await writeFile('$root/pubspec.yaml', '''name: $uiPackage
description: "Design system (theme, tokens, components) — generated by NEAT."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
${deps.toString().trimRight()}

dev_dependencies:
  flutter_lints: ^6.0.0
  spider: ^4.2.3

flutter:
  # Branding assets shipped inside the package, rendered via SvgPictureCustom /
  # ImagePictureCustom (loaded with package: '$uiPackage').
  assets:
    - assets/
''');

    // Shared SVG/image widgets + an assets folder for branding.
    await writeFile(
      '$root/lib/widgets/asset_images.dart',
      ThemeTemplates.assetWidgets(packageName: uiPackage),
    );
    await writeFile('$root/assets/.gitkeep', '');

    // A displayable copy of the logo + typed asset paths (spider-compatible).
    final hasLogo = logoPath.isNotEmpty && File(logoPath).existsSync();
    if (hasLogo) {
      final dest = File('$root/assets/branding/logo.png');
      await dest.create(recursive: true);
      await dest.writeAsBytes(await File(logoPath).readAsBytes());
    }
    await writeFile('$root/spider.yaml', ThemeTemplates.spiderConfig());
    await writeFile('$root/lib/gen/assets.dart', ThemeTemplates.assetsClass(hasLogo: hasLogo));

    // Public barrel.
    final exports = StringBuffer()
      ..writeln("export 'core/theme/app_theme.dart';")
      ..writeln("export 'core/theme/constant/constant.dart';")
      ..writeln("export 'core/theme/typography/typography.dart';")
      ..writeln("export 'widgets/asset_images.dart';")
      ..writeln("export 'gen/assets.dart';");
    for (final c in components) {
      exports.writeln("export 'components/${c.fileName}';");
    }
    await writeFile('$root/lib/$uiPackage.dart', '''/// Public API of the $uiPackage design system.
library;

${exports.toString().trimRight()}
''');
  }

  /// pubspec for the standalone Widgetbook workspace member (depends on `<ui>`).
  /// Named `<app>_widgetbook` — it can't be called `widgetbook` since it depends
  /// on the `widgetbook` package. [useScreenUtil]: see ThemeTemplates
  /// .widgetbookApp's own doc — pub requires a package to declare its own
  /// direct dependency on anything it imports, so this needs its own entry
  /// even though `<ui>` (the path dependency below) already has one too.
  static String widgetbookPubspec(
    String packageName,
    String uiPackage, {
    bool useScreenUtil = false,
  }) {
    final screenUtilDep = useScreenUtil ? '  flutter_screenutil: ^5.9.3\n' : '';
    return '''name: ${packageName}_widgetbook
description: "Interactive component catalog — generated by NEAT."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.25.0
$screenUtilDep  $uiPackage:
    path: ../packages/$uiPackage

dev_dependencies:
  flutter_lints: ^6.0.0
''';
  }
}
