import 'package:neat/features/cicd/domain/models/cicd_state.dart';

class GeneratedFile {
  const GeneratedFile({required this.filename, required this.content});

  final String filename;
  final String content;
}

class GenerateYamlUsecase {
  const GenerateYamlUsecase();

  /// [hasFlavors] (true when envied is on) makes the fastlane lanes flavor-aware
  /// (`--flavor <f> -t lib/main_<f>.dart`).
  List<GeneratedFile> execute(CicdState state, {bool hasFlavors = false}) {
    final files = <GeneratedFile>[];

    if (state.isSelected(CiTool.githubActions)) {
      files.add(
        GeneratedFile(filename: '.github/workflows/flutter.yml', content: _githubActions(state)),
      );
    }
    if (state.isSelected(CiTool.gitlabCi)) {
      files.add(GeneratedFile(filename: '.gitlab-ci.yml', content: _gitlabCi(state)));
    }
    if (state.isSelected(CiTool.codemagic)) {
      files.add(GeneratedFile(filename: 'codemagic.yaml', content: _codemagic(state)));
    }
    if (state.isSelected(CiTool.fastlane)) {
      // fastlane lives under android/ and ios/ — NOT the project root — and reads
      // every account-specific value from the environment (no secrets committed).
      files
        ..add(GeneratedFile(
            filename: 'android/fastlane/Fastfile', content: _androidFastfile(hasFlavors)))
        ..add(GeneratedFile(filename: 'android/fastlane/Appfile', content: _androidAppfile()))
        ..add(GeneratedFile(
            filename: 'android/fastlane/.env.example', content: _androidFastlaneEnv()))
        ..add(GeneratedFile(filename: 'android/Gemfile', content: _gemfile()))
        ..add(GeneratedFile(
            filename: 'android/key.properties.example', content: _keyProperties()))
        ..add(GeneratedFile(filename: 'ios/fastlane/Fastfile', content: _iosFastfile(hasFlavors)))
        ..add(GeneratedFile(filename: 'ios/fastlane/Appfile', content: _iosAppfile()))
        ..add(GeneratedFile(filename: 'ios/fastlane/Matchfile', content: _matchfile()))
        ..add(GeneratedFile(filename: 'ios/fastlane/.env.example', content: _iosFastlaneEnv()))
        ..add(GeneratedFile(filename: 'ios/Gemfile', content: _gemfile()));
    }
    if (state.isSelected(CiTool.shorebird)) {
      files.add(GeneratedFile(filename: 'shorebird.yaml', content: _shorebird(state)));
    }

    return files;
  }

  // ── GitHub Actions ──────────────────────────────────────────────────────────

  String _githubActions(CicdState state) {
    final buf = StringBuffer();
    buf.writeln('# .github/workflows/flutter.yml — generated by NEAT');
    buf.writeln('name: Flutter CI/CD');
    buf.writeln();
    buf.writeln('on:');
    buf.writeln('  push:');
    buf.writeln('    branches: [main, develop]');
    buf.writeln('  pull_request:');
    buf.writeln('    branches: [main]');
    buf.writeln();
    buf.writeln('jobs:');

    if (state.runAnalyze || state.runTests) {
      buf.writeln('  quality:');
      buf.writeln('    runs-on: ubuntu-latest');
      buf.writeln('    steps:');
      buf.writeln('      - uses: actions/checkout@v4');
      buf.writeln('      - uses: subosito/flutter-action@v2');
      buf.writeln('        with:');
      buf.writeln("          channel: 'stable'");
      buf.writeln('          cache: true');
      buf.writeln('      - run: flutter pub get');
      if (state.runAnalyze) {
        buf.writeln('      - run: flutter analyze');
        buf.writeln('      - run: dart format --set-exit-if-changed .');
      }
      if (state.runTests) {
        buf.writeln('      - run: flutter test --coverage');
      }
    }

    if (state.autoDeploy) {
      final needsClause = (state.runAnalyze || state.runTests) ? '\n    needs: quality' : '';
      buf.writeln();
      buf.writeln('  deploy:');
      buf.writeln('    runs-on: macos-latest$needsClause');
      buf.writeln("    if: startsWith(github.ref, 'refs/tags/v')");
      buf.writeln('    steps:');
      buf.writeln('      - uses: actions/checkout@v4');
      buf.writeln('      - uses: subosito/flutter-action@v2');
      if (state.isSelected(CiTool.shorebird)) {
        buf.writeln('      - uses: shorebirdtech/setup-shorebird@v1');
        buf.writeln('      - run: shorebird release android');
        buf.writeln('      - run: shorebird release ios');
      } else if (state.isSelected(CiTool.fastlane)) {
        buf.writeln('      - run: cd ios && bundle install && bundle exec fastlane release');
        buf.writeln('      - run: cd android && bundle install && bundle exec fastlane release');
      }
    }

    return buf.toString();
  }

  // ── GitLab CI ───────────────────────────────────────────────────────────────

  String _gitlabCi(CicdState state) {
    final buf = StringBuffer();
    buf.writeln('# .gitlab-ci.yml — generated by NEAT');
    buf.writeln();
    buf.writeln('image: ghcr.io/cirruslabs/flutter:stable');
    buf.writeln();
    buf.writeln('stages:');
    if (state.runAnalyze || state.runTests) buf.writeln('  - quality');
    if (state.autoDeploy) buf.writeln('  - deploy');
    buf.writeln();
    buf.writeln('cache:');
    buf.writeln('  paths: [.pub-cache/]');
    buf.writeln();

    if (state.runAnalyze || state.runTests) {
      buf.writeln('quality:');
      buf.writeln('  stage: quality');
      buf.writeln('  script:');
      buf.writeln('    - flutter pub get');
      if (state.runAnalyze) {
        buf.writeln('    - flutter analyze');
        buf.writeln('    - dart format --set-exit-if-changed .');
      }
      if (state.runTests) buf.writeln('    - flutter test --coverage');
    }

    if (state.autoDeploy) {
      buf.writeln();
      buf.writeln('deploy:');
      buf.writeln('  stage: deploy');
      buf.writeln('  rules:');
      buf.writeln("    - if: '\$CI_COMMIT_TAG =~ /^v/'");
      buf.writeln('  script:');
      if (state.isSelected(CiTool.shorebird)) {
        buf.writeln('    - shorebird release android');
        buf.writeln('    - shorebird release ios');
      } else if (state.isSelected(CiTool.fastlane)) {
        buf.writeln('    - cd ios && bundle install && bundle exec fastlane release');
        buf.writeln('    - cd android && bundle install && bundle exec fastlane release');
      }
    }

    return buf.toString();
  }

  // ── Codemagic ───────────────────────────────────────────────────────────────

  String _codemagic(CicdState state) {
    final buf = StringBuffer();
    buf.writeln('# codemagic.yaml — generated by NEAT');
    buf.writeln();
    buf.writeln('workflows:');
    buf.writeln('  flutter-workflow:');
    buf.writeln('    name: Flutter CI/CD');
    buf.writeln('    instance_type: mac_mini_m1');
    buf.writeln('    environment:');
    buf.writeln('      flutter: stable');
    buf.writeln('    scripts:');
    buf.writeln('      - name: Install dependencies');
    buf.writeln('        script: flutter pub get');
    if (state.runAnalyze) {
      buf.writeln('      - name: Analyze');
      buf.writeln('        script: flutter analyze');
    }
    if (state.runTests) {
      buf.writeln('      - name: Test');
      buf.writeln('        script: flutter test --coverage');
    }
    if (state.autoDeploy) {
      if (state.isSelected(CiTool.shorebird)) {
        buf.writeln('      - name: Shorebird release');
        buf.writeln('        script: |');
        buf.writeln('          shorebird release android');
        buf.writeln('          shorebird release ios');
      } else {
        buf.writeln('      - name: Build iOS');
        buf.writeln('        script: flutter build ipa --release');
        buf.writeln('      - name: Build Android');
        buf.writeln('        script: flutter build appbundle --release');
      }
    }
    if (state.autoDeploy) {
      buf.writeln('    publishing:');
      buf.writeln('      app_store_connect:');
      buf.writeln('        auth: integration');
      buf.writeln('      google_play:');
      buf.writeln('        credentials: \$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS');
      buf.writeln('        track: internal');
    }

    return buf.toString();
  }

  // ── Fastlane (android/fastlane + ios/fastlane) ───────────────────────────────

  /// Runs the Flutter SDK from the project root (fastlane's cwd is android/ or
  /// ios/, one level down). Overridable via FLUTTER_CMD (CI sets `flutter`).
  static const _flutterHelper = '''
def flutter(*args)
  cmd = ENV.fetch("FLUTTER_CMD", "flutter").split
  Dir.chdir("..") { sh(*cmd, *args) } # fastlane runs in android/ (or ios/); root is one up.
end
''';

  String _androidFastfile(bool hasFlavors) {
    final buildLane = hasFlavors
        ? '''    flavor = (options[:flavor] || "prod").to_s
    flutter("build", "appbundle", "--release", "--flavor", flavor, "-t", "lib/main_#{flavor}.dart")
    aab = "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab"'''
        : '''    flutter("build", "appbundle", "--release")
    aab = "../build/app/outputs/bundle/release/app-release.aab"''';
    return '''# android/fastlane/Fastfile — generated by NEAT
# Secrets are read from the environment (copy fastlane/.env.example → .env).
# Release signing is configured via android/key.properties (git-ignored).
default_platform(:android)
$_flutterHelper
platform :android do
  desc "Build a release app bundle and upload it to Google Play (internal track)."
  desc "Usage: bundle exec fastlane release${hasFlavors ? ' [flavor:dev|staging|prod]' : ''}"
  lane :release do |options|
$buildLane
    upload_to_play_store(
      track: "internal",
      aab: aab,
      json_key: ENV.fetch("PLAY_STORE_JSON_KEY_PATH"),
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
''';
  }

  String _iosFastfile(bool hasFlavors) {
    final buildLane = hasFlavors
        ? '''    flavor = (options[:flavor] || "prod").to_s
    flutter("build", "ipa", "--release", "--flavor", flavor, "-t", "lib/main_#{flavor}.dart")'''
        : '    flutter("build", "ipa", "--release")';
    return '''# ios/fastlane/Fastfile — generated by NEAT
# Secrets are read from the environment (copy fastlane/.env.example → .env).
# Signing uses fastlane match (see Matchfile).
default_platform(:ios)
$_flutterHelper
platform :ios do
  desc "Build a release IPA and upload it to TestFlight."
  desc "Usage: bundle exec fastlane release${hasFlavors ? ' [flavor:dev|staging|prod]' : ''}"
  lane :release do |options|
    setup_ci if ENV["CI"]
    match(type: "appstore", readonly: true)
$buildLane
    upload_to_testflight(
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"],
      ipa: Dir["../build/ios/ipa/*.ipa"].first,
      skip_waiting_for_build_processing: true,
    )
  end
end
''';
  }

  String _androidAppfile() => '''# Read from the environment — nothing project-specific is committed.
json_key_file(ENV["PLAY_STORE_JSON_KEY_PATH"])
package_name(ENV["ANDROID_PACKAGE_NAME_BASE"])
''';

  String _iosAppfile() => '''# Read from the environment — nothing project-specific is committed.
app_identifier(ENV["IOS_BUNDLE_ID"])
apple_id(ENV["APPLE_ID"])
team_id(ENV["APPLE_TEAM_ID"])
''';

  String _matchfile() => '''# fastlane match — shared signing certificates/profiles in a private git repo.
# See https://docs.fastlane.tools/actions/match/
git_url(ENV["MATCH_GIT_URL"])
storage_mode("git")
type("appstore")
app_identifier(ENV["IOS_BUNDLE_ID"])
''';

  String _androidFastlaneEnv() => '''# Copy to android/fastlane/.env and fill in (this file is git-ignored).
# Google Play service-account JSON key (absolute path).
PLAY_STORE_JSON_KEY_PATH=
# Base applicationId (prod). Flavors append .dev / .staging.
ANDROID_PACKAGE_NAME_BASE=com.example.app
# CI sets `flutter` on PATH; locally you may use `fvm flutter`.
FLUTTER_CMD=flutter
''';

  String _iosFastlaneEnv() => '''# Copy to ios/fastlane/.env and fill in (this file is git-ignored).
IOS_BUNDLE_ID=com.example.app
APPLE_ID=
APPLE_TEAM_ID=
# App Store Connect API key (.p8) absolute path, for TestFlight upload.
APP_STORE_CONNECT_API_KEY_PATH=
# Private git repo holding match certificates/profiles.
MATCH_GIT_URL=
FLUTTER_CMD=flutter
''';

  String _gemfile() => '''source "https://rubygems.org"

gem "fastlane", "~> 2.226"
''';

  String _keyProperties() => '''# Copy to android/key.properties and fill in to enable release signing.
# key.properties + keystores (*.jks/*.keystore) are git-ignored — never commit them.
# https://flutter.dev/to/reference-keystore
storePassword=
keyPassword=
keyAlias=upload
storeFile=upload-keystore.jks
''';

  // ── Shorebird ───────────────────────────────────────────────────────────────

  String _shorebird(CicdState state) {
    return '''# shorebird.yaml — generated by NEAT
# https://docs.shorebird.dev

# Your Shorebird app_id (fill after running: shorebird init)
app_id: YOUR_APP_ID

# Auto-patch on every push to main, full release on version tags
release_script: |
  if [[ "\$SHOREBIRD_ENV" == "release" ]]; then
    shorebird release android
    shorebird release ios
  else
    shorebird patch android
    shorebird patch ios
  fi
''';
  }
}
