import 'package:neat/features/cicd/presentation/providers/cicd_provider.dart';

class GeneratedFile {
  const GeneratedFile({required this.filename, required this.content});
  final String filename;
  final String content;
}

class GenerateYamlUsecase {
  const GenerateYamlUsecase();

  List<GeneratedFile> execute(CicdState state) {
    final files = <GeneratedFile>[];

    if (state.isSelected(CiTool.githubActions)) {
      files.add(GeneratedFile(
        filename: '.github/workflows/flutter.yml',
        content: _githubActions(state),
      ));
    }
    if (state.isSelected(CiTool.gitlabCi)) {
      files.add(GeneratedFile(
        filename: '.gitlab-ci.yml',
        content: _gitlabCi(state),
      ));
    }
    if (state.isSelected(CiTool.codemagic)) {
      files.add(GeneratedFile(
        filename: 'codemagic.yaml',
        content: _codemagic(state),
      ));
    }
    if (state.isSelected(CiTool.fastlane)) {
      files.add(GeneratedFile(
        filename: 'fastlane/Fastfile',
        content: _fastfile(state),
      ));
    }
    if (state.isSelected(CiTool.shorebird)) {
      files.add(GeneratedFile(
        filename: 'shorebird.yaml',
        content: _shorebird(state),
      ));
    }

    return files;
  }

  // ── GitHub Actions ──────────────────────────────────────────────────────────

  String _githubActions(CicdState state) {
    final buf = StringBuffer();
    buf.writeln('# .github/workflows/flutter.yml — generated by NEAT');
    buf.writeln('name: Flutter CI/CD');
    buf.writeln();
    buf.writeln('on:');
    buf.writeln('  push:');
    buf.writeln('    branches: [main, develop]');
    buf.writeln('  pull_request:');
    buf.writeln('    branches: [main]');
    buf.writeln();
    buf.writeln('jobs:');

    if (state.runAnalyze || state.runTests) {
      buf.writeln('  quality:');
      buf.writeln('    runs-on: ubuntu-latest');
      buf.writeln('    steps:');
      buf.writeln('      - uses: actions/checkout@v4');
      buf.writeln('      - uses: subosito/flutter-action@v2');
      buf.writeln('        with:');
      buf.writeln("          channel: 'stable'");
      buf.writeln('          cache: true');
      buf.writeln('      - run: flutter pub get');
      if (state.runAnalyze) {
        buf.writeln('      - run: flutter analyze');
        buf.writeln('      - run: dart format --set-exit-if-changed .');
      }
      if (state.runTests) {
        buf.writeln('      - run: flutter test --coverage');
      }
    }

    if (state.autoDeploy) {
      final needsClause =
          (state.runAnalyze || state.runTests) ? '\n    needs: quality' : '';
      buf.writeln();
      buf.writeln('  deploy:');
      buf.writeln('    runs-on: macos-latest$needsClause');
      buf.writeln("    if: startsWith(github.ref, 'refs/tags/v')");
      buf.writeln('    steps:');
      buf.writeln('      - uses: actions/checkout@v4');
      buf.writeln('      - uses: subosito/flutter-action@v2');
      if (state.isSelected(CiTool.shorebird)) {
        buf.writeln('      - uses: shorebirdtech/setup-shorebird@v1');
        buf.writeln('      - run: shorebird release android');
        buf.writeln('      - run: shorebird release ios');
      } else if (state.isSelected(CiTool.fastlane)) {
        buf.writeln('      - run: gem install fastlane');
        buf.writeln('      - run: fastlane ios release');
        buf.writeln('      - run: fastlane android release');
      }
    }

    return buf.toString();
  }

  // ── GitLab CI ───────────────────────────────────────────────────────────────

  String _gitlabCi(CicdState state) {
    final buf = StringBuffer();
    buf.writeln('# .gitlab-ci.yml — generated by NEAT');
    buf.writeln();
    buf.writeln('image: ghcr.io/cirruslabs/flutter:stable');
    buf.writeln();
    buf.writeln('stages:');
    if (state.runAnalyze || state.runTests) buf.writeln('  - quality');
    if (state.autoDeploy) buf.writeln('  - deploy');
    buf.writeln();
    buf.writeln('cache:');
    buf.writeln('  paths: [.pub-cache/]');
    buf.writeln();

    if (state.runAnalyze || state.runTests) {
      buf.writeln('quality:');
      buf.writeln('  stage: quality');
      buf.writeln('  script:');
      buf.writeln('    - flutter pub get');
      if (state.runAnalyze) {
        buf.writeln('    - flutter analyze');
        buf.writeln('    - dart format --set-exit-if-changed .');
      }
      if (state.runTests) buf.writeln('    - flutter test --coverage');
    }

    if (state.autoDeploy) {
      buf.writeln();
      buf.writeln('deploy:');
      buf.writeln('  stage: deploy');
      buf.writeln("  rules:");
      buf.writeln("    - if: '\$CI_COMMIT_TAG =~ /^v/'");
      buf.writeln('  script:');
      if (state.isSelected(CiTool.shorebird)) {
        buf.writeln('    - shorebird release android');
        buf.writeln('    - shorebird release ios');
      } else if (state.isSelected(CiTool.fastlane)) {
        buf.writeln('    - gem install fastlane');
        buf.writeln('    - fastlane ios release');
        buf.writeln('    - fastlane android release');
      }
    }

    return buf.toString();
  }

  // ── Codemagic ───────────────────────────────────────────────────────────────

  String _codemagic(CicdState state) {
    final buf = StringBuffer();
    buf.writeln('# codemagic.yaml — generated by NEAT');
    buf.writeln();
    buf.writeln('workflows:');
    buf.writeln('  flutter-workflow:');
    buf.writeln('    name: Flutter CI/CD');
    buf.writeln('    instance_type: mac_mini_m1');
    buf.writeln('    environment:');
    buf.writeln('      flutter: stable');
    buf.writeln('    scripts:');
    buf.writeln('      - name: Install dependencies');
    buf.writeln('        script: flutter pub get');
    if (state.runAnalyze) {
      buf.writeln('      - name: Analyze');
      buf.writeln('        script: flutter analyze');
    }
    if (state.runTests) {
      buf.writeln('      - name: Test');
      buf.writeln('        script: flutter test --coverage');
    }
    if (state.autoDeploy) {
      if (state.isSelected(CiTool.shorebird)) {
        buf.writeln('      - name: Shorebird release');
        buf.writeln('        script: |');
        buf.writeln('          shorebird release android');
        buf.writeln('          shorebird release ios');
      } else {
        buf.writeln('      - name: Build iOS');
        buf.writeln('        script: flutter build ipa --release');
        buf.writeln('      - name: Build Android');
        buf.writeln('        script: flutter build appbundle --release');
      }
    }
    if (state.autoDeploy) {
      buf.writeln('    publishing:');
      buf.writeln('      app_store_connect:');
      buf.writeln('        auth: integration');
      buf.writeln('      google_play:');
      buf.writeln('        credentials: \$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS');
      buf.writeln('        track: internal');
    }

    return buf.toString();
  }

  // ── Fastlane ────────────────────────────────────────────────────────────────

  String _fastfile(CicdState state) {
    return '''# fastlane/Fastfile — generated by NEAT

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end

platform :android do
  desc "Deploy to Google Play"
  lane :release do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
''';
  }

  // ── Shorebird ───────────────────────────────────────────────────────────────

  String _shorebird(CicdState state) {
    return '''# shorebird.yaml — generated by NEAT
# https://docs.shorebird.dev

# Your Shorebird app_id (fill after running: shorebird init)
app_id: YOUR_APP_ID

# Auto-patch on every push to main, full release on version tags
release_script: |
  if [[ "\$SHOREBIRD_ENV" == "release" ]]; then
    shorebird release android
    shorebird release ios
  else
    shorebird patch android
    shorebird patch ios
  fi
''';
  }
}
