import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:neat/features/theme_engine/presentation/providers/theme_engine_provider.dart';
import 'package:neat_ui/neat_ui.dart';

Future<void> _openPlayground() async {
  await Process.run('open', ['https://rydmike.com/flexcolorscheme/themesplayground-latest/']);
}

class FlexColorSchemeTab extends HookConsumerWidget {
  const FlexColorSchemeTab({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final codeCtrl = useTextEditingController(
      text: ref.read(themeEngineProvider.select((s) => s.flexColorSchemeCode)) ?? '',
    );

    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Playground link
          Align(
            alignment: Alignment.centerRight,
            child: OutlinedButton.icon(
              onPressed: _openPlayground,
              icon: const Icon(Icons.open_in_new, size: 14),
              label: const Text('Open Playground', style: TextStyle(fontSize: 12)),
              style: OutlinedButton.styleFrom(
                foregroundColor: Palette.colorPrimaryCyan,
                side: const BorderSide(color: Palette.colorPrimaryCyan),
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // ── Code editor ──────────────────────────────────────────────────
          SectionHeader(
            iconSize: 16,
            fontSize: 14,
            icon: Icons.code_outlined,
            label: 'Import Configuration',
          ),
          const SizedBox(height: 16),

          DecoratedBox(
            decoration: BoxDecoration(
              color: const Color(0xFF0D0D0F),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Colors.white10),
            ),
            child: Column(
              children: [
                // Top bar
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                  decoration: const BoxDecoration(
                    color: Color(0xFF18181C),
                    borderRadius: BorderRadius.vertical(top: Radius.circular(10)),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.insert_drive_file_outlined, size: 14, color: Colors.white38),
                      const SizedBox(width: 8),
                      const Text(
                        'IMPORT CONFIGURATION',
                        style: TextStyle(
                          color: Colors.white38,
                          fontSize: 10,
                          fontWeight: FontWeight.bold,
                          letterSpacing: 1.0,
                        ),
                      ),
                    ],
                  ),
                ),

                // Code area
                TextField(
                  controller: codeCtrl,
                  onChanged: (value) {
                    final code = value.trim();
                    ref
                        .read(themeEngineProvider.notifier)
                        .setFlexColorSchemeCode(code.isEmpty ? null : code);
                  },
                  maxLines: 14,
                  style: const TextStyle(
                    color: Color(0xFF9ECE6A),
                    fontFamily: 'monospace',
                    fontSize: 12,
                    height: 1.6,
                  ),
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    contentPadding: const EdgeInsets.all(16),
                    hintText:
                        'Paste the full code generated by the FlexColorScheme playground.\n'
                        'You can paste everything — imports, class, light & dark themes.\n'
                        'NEAT will inject its own extensions automatically.\n\n'
                        'import \'package:flex_color_scheme/flex_color_scheme.dart\';\n'
                        'import \'package:flutter/material.dart\';\n'
                        '...\n'
                        'abstract final class Palette {\n'
                        '  static ThemeData light = FlexThemeData.light(...);\n'
                        '  static ThemeData dark  = FlexThemeData.dark(...);\n'
                        '}',
                    hintStyle: const TextStyle(
                      color: Colors.white12,
                      fontFamily: 'monospace',
                      fontSize: 12,
                      height: 1.6,
                    ),
                  ),
                ),

                // Footer hint
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  child: Row(
                    children: [
                      const Icon(Icons.info_outline, size: 11, color: Colors.white12),
                      const SizedBox(width: 6),
                      const Expanded(
                        child: Text(
                          'Paste the full playground output — NEAT handles the rest',
                          style: TextStyle(color: Colors.white12, fontSize: 10),
                        ),
                      ),
                      const Text(
                        'FLEXCOLORSCHEME 8.x',
                        style: TextStyle(color: Colors.white12, fontSize: 10, letterSpacing: 0.8),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 24),

          // Packaging — available in FlexColorScheme too (not just Custom M3).
          // SectionHeader(
          //   iconSize: 16,
          //   fontSize: 14,
          //   icon: Icons.widgets_outlined,
          //   label: 'Packaging',
          // ),
          // const SizedBox(height: 12),
          // _SimpleToggleCard(
          //   icon: Icons.widgets_outlined,
          //   title: 'Extract UI into a package',
          //   description:
          //       'Move theme, tokens & components into a `<app>_ui` workspace package. '
          //       'The app and Widgetbook depend on it — clean decoupling.',
          //   enabled: state.extractUiPackage,
          //   onChanged: notifier.setExtractUiPackage,
          // ),
          //
          // const SizedBox(height: 24),
          // SectionHeader(
          //   iconSize: 16,
          //   fontSize: 14,
          //   icon: Icons.image_outlined,
          //   label: 'Branding (App Icon & Splash)',
          // ),
          // const SizedBox(height: 16),
          // _BrandingCard(
          //   logoPath: state.logoPath,
          //   onPick: () async {
          //     final result = await FilePicker.pickFiles(
          //       type: FileType.custom,
          //       allowedExtensions: const ['png'],
          //     );
          //     final path = result?.files.single.path;
          //     if (path != null) notifier.setLogoPath(path);
          //   },
          //   onRemove: () => notifier.setLogoPath(''),
          // ),
          const SizedBox(height: 24),
        ],
      ),
    );
  }
}
